AET-23: Aether ERD, entity extraction
eHealthAfrica/aether pull request #1
Opened 2017-11-13 16:09 UTC by quesebifurcan

- Change gather2 models to reflect the aether ERD
- Add entity extraction utilities

2017-11-21 11:20 UTC, admbtlr requested changes
We should figure out a strategy for refactoring this PR. I just discussed it with Fredrik, and we're going to try and merge his fixed tests into this branch, so that we can then refactor in confidence (TM)

2017-11-21 11:20 UTC, admbtlr commented on gather2-common/gather2/common/core/utils.py
> +def get_surveys_url(mapping_id=''):
We should probably change this function name too

2017-11-21 11:20 UTC, admbtlr commented on gather2-common/gather2/common/core/utils.py
> +def get_survey_responses_url(mapping_id, response_id=None):
Also this function name (i.e. `get_mapping_responses_url`). In fact actually we might want to review the nomenclature here, since you don't really "respond" to a mapping, but you could "submit". So ideally this would be `get_mapping_submissions_url`, but I guess that would involved a whole load of other changes.

2017-11-21 11:20 UTC, admbtlr commented on gather2-common/gather2/common/core/utils.py
>          raise Exception('Cannot submit response without survey!')
Change this error message

2017-11-21 11:20 UTC, admbtlr commented on gather2-core/gather2/core/api/models.py
> +class Response(models.Model):
`Submission`?

2017-11-21 11:20 UTC, admbtlr commented on gather2-core/gather2/core/api/utils.py
> +    mapping = mapping_definition
Is this necessary?

2017-11-21 11:20 UTC, admbtlr commented on gather2-core/gather2/core/api/utils.py
> +    # Called via #!none acts as a dummy instruction when you need to the first
Can you make this comment make sense?

2017-11-21 11:20 UTC, admbtlr commented on gather2-core/gather2/core/api/utils.py
> +        # create as little as the heirarchy as required
"make the hIErarcy as simple as possible"?

2017-11-21 11:20 UTC, admbtlr commented on gather2-core/gather2/core/api/utils.py
> +    # the proper funciton
funcTIon

2017-11-21 11:20 UTC, admbtlr commented on gather2-core/gather2/core/api/utils.py
> +        raise ValueError("No action by name %s" % action)
No action WITH name

2017-11-21 11:20 UTC, admbtlr commented on gather2-core/gather2/core/api/utils.py
> +    data["aether_errors"] = []
This is going to throw a TypeError if there is no `response_data`

2017-11-21 11:20 UTC, admbtlr commented on gather2-core/gather2/core/api/utils.py
> +    # entitie names that have requirements
entitY

2017-11-21 11:20 UTC, admbtlr commented on gather2-core/gather2/core/api/utils.py
> +def extract_entity(requirements, response_data, entity_stubs):
This is a huge function - can we break it up?

2017-11-21 11:20 UTC, admbtlr commented on gather2-core/gather2/core/api/utils.py
> +    for entity_name in required_entities:
I know that this is not the first time this terminology has been used, but I think we should probably call this `entity_type`. We're in danger of confusing entities with entity definitions, and I think we should do everything we can to make the distinction clearer. 

(Years ago, I worked as a developer and then trainer at a CMS company; our CMS had "items" and "items types", and it caused endless confusion for all our users)

2017-11-21 11:20 UTC, admbtlr commented on gather2-core/gather2/core/api/utils.py
> +            while i <= count-1:
why not `while i < count`?

2017-11-21 11:20 UTC, admbtlr commented on gather2-core/gather2/core/api/utils.py
> +                    if len(matches) < 2:
Why not `if len(matches) == 1`? If there are 0 matches, line 305 will blow up.

2017-11-21 11:20 UTC, admbtlr commented on gather2-core/gather2/core/api/utils.py
> +    entities = get_entity_definitions(mapping_definition, schemas)
Again here, we should always try and use `entity_defs` or similar

2017-11-21 11:20 UTC, admbtlr commented on gather2-core/gather2/core/api/utils.py
> +    for name, entity_instances in entities.items():
See? now you have to use `entity_instances` because you used `entities` earlier :)

2017-11-21 11:20 UTC, admbtlr commented on gather2-core/gather2/core/apps.py
> +        # from .api import signals  # flake8: noqa
delete

2017-11-21 11:20 UTC, admbtlr commented on gather2-core/gather2/core/tests/test_apps.py
>          # this is only valid in tests, the correct name is `gather2.core`
delete

2017-11-21 11:20 UTC, admbtlr commented on gather2-odk-importer/gather2/odk/api/core_utils.py
> +import os
So this is the file you had to create because the `common` module changes weren't being picked up, right? We need to sort that out...

2017-11-21 14:16 UTC, quesebifurcan commented on gather2-odk-importer/gather2/odk/api/core_utils.py
> +import os
The common module changes will be picked up if you run `./scripts/upgrade_all.sh` and rebuild all containers (that will take a while).

2017-11-23 13:13 UTC, admbtlr commented on gather2-core/gather2/core/api/utils.py
> +    # the proper funciton
instRuction

2017-11-27 01:01 UTC, realdouno commented on gather2-core/gather2/core/apps.py
> +        # from .api import signals  # flake8: noqa
Done

2017-11-27 01:03 UTC, realdouno commented on gather2-odk-importer/gather2/odk/api/core_utils.py
> +import os
Fixed

2017-11-27 01:05 UTC, realdouno commented on gather2-common/gather2/common/core/utils.py
> +def get_surveys_url(mapping_id=''):
Fixed

2017-11-27 01:05 UTC, realdouno commented on gather2-common/gather2/common/core/utils.py
>          raise Exception('Cannot submit response without survey!')
Fixed

2017-11-27 01:09 UTC, realdouno commented on gather2-core/gather2/core/api/utils.py
> +    # the proper funciton
Fixed

2017-11-27 01:11 UTC, realdouno commented on gather2-core/gather2/core/api/utils.py
> +        raise ValueError("No action by name %s" % action)
Fixed

2017-11-27 01:14 UTC, realdouno commented on gather2-core/gather2/core/api/utils.py
> +    # entitie names that have requirements
Fixed

2017-11-27 03:28 UTC, realdouno commented on gather2-core/gather2/core/api/models.py
> +class Response(models.Model):
Just to clarify, are you wanting us to replace `Response` by `Submission`?

2017-11-27 03:30 UTC, realdouno commented on gather2-common/gather2/common/core/utils.py
> +def get_survey_responses_url(mapping_id, response_id=None):
`get_survey_responses_url` has been changed to `get_mapping_responses_url`. We can discuss this change in nomenclature during the standup

2017-11-27 03:37 UTC, realdouno commented on gather2-core/gather2/core/api/utils.py
> +    # Called via #!none acts as a dummy instruction when you need to the first
@shawnsarwar

2017-11-27 03:38 UTC, realdouno commented on gather2-core/gather2/core/api/utils.py
> +        # create as little as the heirarchy as required
@shawnsarwar can confirm

2017-11-27 04:52 UTC, realdouno commented on gather2-core/gather2/core/tests/test_apps.py
>          # this is only valid in tests, the correct name is `gather2.core`
This test for the verbose_ name of the app. I am not sure why we need to delete it

2017-11-27 05:19 UTC, realdouno commented on gather2-core/gather2/core/api/utils.py
> +    mapping = mapping_definition
Not really! Removed it

2017-11-27 05:23 UTC, realdouno commented on gather2-core/gather2/core/api/utils.py
> +    data["aether_errors"] = []
`response_data` is assigned  `response.payload` and the payload is required when posting a  response so it's unlikely that we have no `response_data`. But I have set `data` to an empty dictionary in case there is no `response_data`

2017-11-27 13:23 UTC, admbtlr approved these changes
Pending merge of Douno's branch

2017-12-04 10:21 UTC, merged