Aether 23 kafka
eHealthAfrica/aether pull request #10
Opened 2017-11-27 20:30 UTC by djmoran64

This one is ready to go, fixed the test failures.  Updated the docker

2017-11-28 14:46 UTC, admbtlr requested changes

2017-11-28 14:46 UTC, admbtlr commented on .travis.yml
> +# These were causing travis to fail tests
Just remove these lines

2017-11-28 14:46 UTC, admbtlr commented on kafka/data-src/AetherDB.json
> +    "connection.url": "jdbc:postgresql://db:5432/gather2?user=postgres",
Should this be `aether` instead of `gather2`? Can you check this against Douno's renaming PR pls?

2017-11-28 15:03 UTC, quesebifurcan approved these changes
Tried running it locally without running into any issues 👍

2017-11-28 15:28 UTC, djmoran64 commented on .travis.yml
> +# These were causing travis to fail tests
Done.

2017-11-28 15:30 UTC, djmoran64 commented on kafka/data-src/AetherDB.json
> +    "connection.url": "jdbc:postgresql://db:5432/gather2?user=postgres",
It should, but if I change here it will break this branch and the tests may not pass.  I didn't know if that really matters or if I should wait until after douno’s merge.

2017-11-29 14:11 UTC, djmoran64 commented
With the Issues that encountered with Kafka, the team decided to hold off on this merge for now.  We will use logstash in the same way that we did for the demo and commit that after the big gather -> aether merge

2017-11-29 14:11 UTC, closed without merging