aether-38: extend jsonpath_ng with custom wildcards
eHealthAfrica/aether pull request #11
Opened 2017-11-28 10:20 UTC by quesebifurcan

Resolves https://jira.ehealthafrica.org/browse/AET-38

TODO:
 - [x] add a predicate function `is_custom_jsonpath` + some more tests.

2017-11-28 14:55 UTC, admbtlr requested changes

2017-11-28 14:55 UTC, admbtlr commented on gather2-core/gather2/core/api/utils.py
> +custom_jsonpath_wildcard_regex = re.compile('[a-zA-Z0-9_-]+\*')
Do we need a `.` in there to allow for more nested json paths, e.g. `$.facility.dose-*.id`?

2017-11-28 15:07 UTC, quesebifurcan commented on gather2-core/gather2/core/api/utils.py
> +custom_jsonpath_wildcard_regex = re.compile('[a-zA-Z0-9_-]+\*')
Good point -- @shawnsarwar said yesterday that aet-38 should only handle "top-level" custom wildcards. Which might be a good call -- the nested implementation would be significantly more complicated.

2017-11-28 15:17 UTC, quesebifurcan commented on gather2-core/gather2/core/api/utils.py
> +custom_jsonpath_wildcard_regex = re.compile('[a-zA-Z0-9_-]+\*')
Come to think of it, I should probably add some more tests to make sure that we always fall back to `jsonpath_ng.parse` when we should. Here's a good list: https://github.com/json-path/JsonPath#path-examples

2017-12-04 11:26 UTC, admbtlr commented on gather2-core/gather2/core/api/utils.py
> +custom_jsonpath_wildcard_regex = re.compile('[a-zA-Z0-9_-]+\*')
Yup, good call on the tests. And fair enough about ignoring nesting for now.

2017-12-04 11:26 UTC, admbtlr approved these changes

2017-12-04 11:27 UTC, merged