feat: test aether connect
eHealthAfrica/aether pull request #124
Opened 2018-04-05 14:41 UTC by shawnsarwar

This PR pertains to Aether Utilities (python client, salad-bar and data mocker); moving them into a file structure that makes sense and using them to perform integration tests.

To test integration run scripts/test_integration.sh
Integration tests run as part of scripts/test_all.sh

Integration tests live in "test-aether-integration-module"; suggest a better name, please.

The following functionality is tested:
- Automated registration of a schema using saladbar
- Automated generation of entities against the registered schemas using data mocker.
- Automated push from Aether -> Aether Connect using the Aether Producer
- Consistency check of data generated against the entities which can be found in Kafka.

I used pytest fixtures to handle the various resource connections. If you're curious they're in the __init__.py of /test-aether-integration-module/test/

We also have to run different parts of the integration test with python2 and python3, thanks to schema-salad-tool's using the python2 avro library. pip2 and pip3 keep things clean in the docker environment and pytest allows a function annotation that we've written which skips tests pertaining to the wrong version of python. The python2 tests run first since they also setup the schemas.

2018-04-09 09:01 UTC, quesebifurcan requested changes

2018-04-09 09:01 UTC, quesebifurcan commented on aether-producer/entrypoint.sh
> +        #setup_initial_data
Commented code, can we remove these lines?

2018-04-09 09:01 UTC, quesebifurcan commented on aether-utils/aether-client/entrypoint.sh
> +        echo 'start'
Is this used at all? Or just for debugging purposes?

2018-04-09 09:01 UTC, quesebifurcan commented on aether-utils/aether-mock-data/entrypoint.sh
> +set -e
If possible, I'd prefer the same header as in the other bash files:
```
set -Eeuox pipefail
```
Just to limit the number of runtime surprises.

2018-04-09 09:01 UTC, quesebifurcan commented on aether-utils/aether-mock-data/entrypoint.sh
> +    ;;
Same here -- if they aren't really used, we could remove them (and update the help description).

2018-04-10 11:31 UTC, shawnsarwar reviewed
Fixed issues raised.

2018-04-10 11:31 UTC, quesebifurcan approved these changes

2018-04-10 11:35 UTC, merged