Mock ui inputs entity types
eHealthAfrica/aether pull request #131
Opened 2018-04-12 19:58 UTC by lordmallam

#### What does this PR do
Loads mock schema and converts to markup for pipeline input and entity types

2018-04-13 07:45 UTC, obdulia-losantos commented on aether-ui/package.json
> +    "avro-js":"^1.8.2",
Could you change to `~1.8.0`? 

The last time we included a `^1.8.x` there was a breaking change in the `1.9.0` release, not in the `2.0.0` that *unexpectedly* broke the deployment :see_no_evil: 

We try to skip these problems being a little bit "conservative".

2018-04-13 07:46 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/utils/index.jsx
> +
This is an utility file, so no "react" components should be declared here... Maybe you can create a common component with this.

2018-04-13 07:48 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/sections/input.jsx
> +              Your schema for this pipeline will be displayed here once you have added an AVRO schema.
Now that we are in the point of refactoring and normalizing everything, would you mind using `FormattedMessage` for the texts? :grimacing:

2018-04-13 07:49 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/mock/schema_input.mock.jsx
> +        'doc': `Type inferred from ${'1972'}`
Curious magic number :smile:

2018-04-13 07:51 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +          { this.props.selectedPipeline ? this.props.selectedPipeline.name : 'Select a pipeline' }
In this page the `selectedPipeline` is never `null` :wink:

2018-04-13 07:57 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +          { this.props.selectedPipeline ? this.props.selectedPipeline.name : 'Select a pipeline' }
Well, actually, if there is no `selectedPipeline` the component should redirect to `/ `, shouldn't it? :thinking:

2018-04-13 08:14 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/mock/schema_input.mock.jsx
> +        'doc': `Type inferred from ${'1972'}`
Exactly what I thought

2018-04-13 08:18 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +          { this.props.selectedPipeline ? this.props.selectedPipeline.name : 'Select a pipeline' }
Yeah it should and did, until i commented the code out to prevent compulsory pipeline creation due to our approach of implementing mappings first then walk backwards. https://github.com/eHealthAfrica/aether/blob/mock-ui-inputs-entity-types/aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx#L29

2018-04-13 08:26 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +          { this.props.selectedPipeline ? this.props.selectedPipeline.name : 'Select a pipeline' }
In that case, could you add a comment there? I'm quite sure that we are going to forget to undo this once we finish with the mappings... pretty sure! :joy:

2018-04-13 09:09 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/components/common.jsx
> +export const schemaToMarkup = schema => {
I should have explained better. :see_no_evil: 

I meant to create a common component in this folder `components`, something like this:

`aether-ui/aether/ui/assets/apps/components/AvroSchemaViewer.jsx`

```javascript
import React from 'react'
import avro from 'avro-js'

class AvroSchemaViewer extends Component {
  render {
    const schema = avro.parse(this.props.schema)

    return (
      // here it goes...
    )
  }
}

```

2018-04-13 09:15 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +          { this.props.selectedPipeline ? this.props.selectedPipeline.name : 'Select a pipeline' }
:nerd_face:

2018-04-13 09:17 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/sections/input.jsx
> +          }
Dummy question, the input can only be an avro schema or also a real submission json? :thinking: 
I'm trying to understand what are we building here.

2018-04-13 09:47 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/pipeline/sections/input.jsx
> +          }
It can be submission json, but for now just schema as discussed earlier with @quesebifurcan and @adamvert

2018-04-13 09:49 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/pipeline/sections/input.jsx
> +          }
Thus, `avro.parse()` in the logic, if it fails then fall back to submission json mode. But a discussion for another day

2018-04-13 09:56 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/sections/input.jsx
> +          }
:+1:

2018-04-13 11:48 UTC, obdulia-losantos commented on aether-ui/package.json
> +    "avro-js":"~1.8.2",
Thanks!

2018-04-13 11:49 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +                <AvroSchemaViewer schema={MockInputSchema} />
Are you sure about this approach?

2018-04-13 11:52 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +                <AvroSchemaViewer schema={MockInputSchema} />
Some refactoring will be needed when including the submission json mode, but that requirement isn't quite clear for now

2018-04-13 12:08 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +                <AvroSchemaViewer schema={MockInputSchema} />
Right! So let's merge this and continue working from it :clap:

2018-04-13 12:08 UTC, obdulia-losantos approved these changes

2018-04-13 12:10 UTC, sabeen commented
hey, shouldn't we wait also for the styles?
or does it block you?

2018-04-13 12:11 UTC, obdulia-losantos commented
Do you want to do them here or in another PR? It's up to you...

2018-04-13 12:12 UTC, sabeen commented
I think it belongs here…

2018-04-13 12:13 UTC, obdulia-losantos requested changes
waiting for styles...

2018-04-17 10:18 UTC, obdulia-losantos commented
@lordmallam @sabeen let me know when it's done to review it again :nerd_face:

2018-04-17 15:38 UTC, lordmallam commented
@obdulia-losantos all done.

2018-04-17 15:40 UTC, obdulia-losantos commented
:eyes:

2018-04-18 09:20 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/components/AvroSchemaViewer.jsx
> +export default AvroSchemaViewer
Already reviewed! :+1:

2018-04-18 09:20 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/components/AvroSchemaViewer.spec.jsx
> +})
Already reviewed! :+1:

2018-04-18 09:22 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/components/EntityTypeViewer.jsx
> +export default EntityTypeViewer
Entity types are part of the data model then the app, so this file shouldn't be here (the "agnostic" folder) but within the rest of pipeline files... don't you think so?

2018-04-18 09:25 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/sections/entityTypes.jsx
> +          <label className='form-label'>paste Entity Type definitions</label>
Missing `FormattedMessage` :de: :gb: :fr: ...

2018-04-18 09:25 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/sections/entityTypes.jsx
> +          <textarea type='text' className='monospace' value={this.state.entityTypesSchema} onChange={this.onSchemaTextChanged.bind(this)} placeholder='Enter your schema'
same comment for `placeholder`

2018-04-18 09:28 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/sections/input.jsx
> +            rows='10' />
same comment as above

2018-04-18 09:33 UTC, obdulia-losantos commented on aether-ui/package.json
> +    "avro-js":"~1.8.2",
We are going to need that this library creates a random input based on the Avro schema to validate the mapping rules, is it possible?

I will answer myself, yes, it does. :grimacing: 

```javascript
// We can also parse a JSON-stringified schema:
var type = avro.parse('{"type": "fixed", "name": "Id", "size": 4}');
var id = type.random(); // E.g. Buffer([48, 152, 2, 123])
```

2018-04-18 09:34 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/components/EntityTypeViewer.jsx
> +export default EntityTypeViewer
This is just a viewer component like the avro schema viewer, and in this case entity types aren't part of the data model as they are only refs to facilitate the creation of maps

2018-04-18 09:36 UTC, obdulia-losantos commented
Regarding the naming convention we agreed on, the filenames should change from `input` to `Input` and so on... I now it's a silly change but also indicates that the content is a component :wink:

2018-04-18 09:47 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/components/EntityTypeViewer.jsx
> +export default EntityTypeViewer
I thought that the Entity types were an important part of the data model and would be pushed to kernel within the avro schema and the mapping rules :thinking: 
The problems of arriving late to the discussions :stuck_out_tongue: 

Anyway, this is not a blockage and can stay here as an "agnostic" viewer :+1:

2018-04-18 10:08 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/sections/input.jsx
> +          <textarea type='text' className='monospace' value={this.state.inputSchema} onChange={this.onSchemaTextChanged.bind(this)} placeholder='Enter your schema'
On the other hand, could it have a length less than 100 chars if possible (it's hard to read without wrapping the text)
:joy_cat:

2018-04-18 10:17 UTC, obdulia-losantos requested changes
looks awesome!

2018-04-18 11:27 UTC, obdulia-losantos approved these changes
:clap:

2018-04-18 13:42 UTC, merged