feat(pipeline): data model with validation
eHealthAfrica/aether pull request #132
Opened 2018-04-13 10:26 UTC by obdulia-losantos

I'm trying to understand how the data model could be. Thereby I will have a better comprehension on what can be done in the frontend.

So far this is what I understood, I'm not sure of the data model but I think it's better if we make our comments here and redesign the data model. So feel free to make any comment, push commits with better designs and whatever you feel will help.

I'm not talking about how to communicate with kernel to validate the data or push it to create the project structure once everything is done... it's just about the data model needed to work on the frontend side.

Thanks!

2018-04-17 09:48 UTC, quesebifurcan reviewed
Looks good! Just one comment re:error details (see above)

2018-04-17 09:48 UTC, quesebifurcan commented on aether-ui/aether/ui/api/models.py
> +            )
I wonder if it's necessary to save the error details in the database -- this is potentially also something which could be kept in the client state. And whenever we re-open a Pipeline, we just run the validation rules again (we'll have to do that anyway to fill the `output` field).

2018-04-17 09:58 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/models.py
> +            )
So, in your opinion it's better to call the validation method from the frontend every time you change the something in the pipeline.  :thinking: makes sense!

My concern was that the first page, pipeline list, shows the number of errors and that means that you are going to call the validation method every time the page is refreshed/loaded for each available pipeline. I was trying to avoid that.

2018-04-17 10:00 UTC, quesebifurcan commented on aether-ui/aether/ui/api/models.py
> +            )
I think both methods would work; it's also fine with me to have everything in one place like you do now. Might make it easier to test. A field `error_count` would also work.

2018-04-18 08:53 UTC, quesebifurcan requested changes

2018-04-18 08:53 UTC, quesebifurcan commented on aether-ui/aether/ui/api/models.py
> +    #      ['xpath-input-1', 'xpath-entity-type-1'],
Maybe change `xpath` to `jsonpath` to clarify that the input is always json?

2018-04-18 08:54 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/models.py
> +    #      ['xpath-input-1', 'xpath-entity-type-1'],
:+1:

2018-04-18 10:02 UTC, quesebifurcan approved these changes

2018-04-18 10:16 UTC, obdulia-losantos commented
@lordmallam I'll wait for your comments since this will affect what we, mostly you, are building in the frontend. :grimacing:

2018-04-18 11:32 UTC, obdulia-losantos commented
Reviewing #131 I saw that the entity types go in one text area, should I change the data model to reflect this and speed up the frontend develop? @lordmallam

2018-04-18 11:54 UTC, lordmallam commented
Yes, as far as i know the entityTypes on the ui will remain a json to generate a visual representation of the types for each pipeline

2018-04-18 11:59 UTC, obdulia-losantos commented
Ok, changing again! :D

2018-04-18 12:02 UTC, lordmallam commented
I think we will also need a way to associate the pipeline with a specific project to allow pipeline config for multiple projects (data submission sources)

2018-04-18 12:10 UTC, obdulia-losantos commented
Yeah! But we should discuss this point deeper and find out an easy way to do that :thinking: 

Maybe when we finalize the current tasks :building_construction:

2018-04-18 14:05 UTC, lordmallam approved these changes

2018-04-18 14:05 UTC, lordmallam commented on aether-ui/aether/ui/api/models.py
> +    +------------------+             +------------------+
First question: how do you come up with these amazing in-code ERDs? 😍

2018-04-18 14:08 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/models.py
> +    +------------------+             +------------------+
:joy: 

Made them manually! Takes time but they are really useful to have the big picture. ;-)

2018-04-18 14:09 UTC, merged