Aet ui style mapping
eHealthAfrica/aether pull request #144
Opened 2018-04-30 13:27 UTC by sabeen

rearrangement of mapping buttons.
The error log moves from mapping section to output section.

2018-04-30 14:11 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Mapping.jsx
> +          <h3 className='title-medium'>Mapping rules</h3>
`FormattedMessage` :see_no_evil:

2018-04-30 14:13 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Output.jsx
> +          <h3 className='title-medium'>Mapping Errors</h3>
`FormattedMessage` :see_no_evil:

2018-04-30 14:14 UTC, sabeen commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Mapping.jsx
> +          <h3 className='title-medium'>Mapping rules</h3>
ok, and also for all the other headlines. got it. ;-)

2018-04-30 14:14 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Output.jsx
> +          <h3 className='title-medium'>Output Data</h3>
`FormattedMessage` :see_no_evil:

2018-04-30 14:15 UTC, obdulia-losantos requested changes
:fr: :gb: :de: :es: and so on...

2018-05-02 07:54 UTC, obdulia-losantos approved these changes

2018-05-02 07:56 UTC, merged