Aet ui push to kernel
eHealthAfrica/aether pull request #151
Opened 2018-05-04 08:31 UTC by lordmallam

#### What does this PR do?
Implements the pipeline publish api endpoint

- Transforms pipeline data into kernel objects (project, schema, mapping)
- Checks if the pipeline objects have links to existing kernel objects (if yes, to be handled in an upcoming PR; if no, creates a new kernel object and save reference to the object on the UI pipeline)

#### How to test
Make a `GET` request `/ui/publish/<pipeline_id>/<project_name>` `pipeline_id` : Id of a pipeline with valid mappings
On kernel, make a submission with the mapping created, Entities should be generated as expected

#### Related JIRA Tickets
[AET-220](https://jira.ehealthafrica.org/browse/AET-220)
[AET-222](https://jira.ehealthafrica.org/browse/AET-222)
[AET-223](https://jira.ehealthafrica.org/browse/AET-223)

2018-05-08 07:25 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/tests/test_utils.py
> +        try:
is it a good practice to use `try-catch` within a test? just asking :thinking:

2018-05-08 07:59 UTC, lordmallam commented on aether-ui/aether/ui/api/tests/test_utils.py
> +        try:
hehehehe.. nope. That was a test within a test. Ill take that out

2018-05-08 08:12 UTC, quesebifurcan commented
Are there any alternatives to using a `GET` request to publish the pipeline? Just asking, since `GET`s do not usually have any side effects.

2018-05-08 08:27 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/views.py
> +def PublishPipeline(requests, pipelineid, projectname):
Could it be possible instead of using an external method outside the ViewSet to include it inside?

https://www.django-rest-framework.org/api-guide/viewsets/#marking-extra-actions-for-routing

```python
from django.shortcuts import get_object_or_404
from rest_framework.decorators import action


class PipelineViewSet(viewsets.ModelViewSet):
    queryset = models.Pipeline.objects.all()
    serializer_class = serializers.PipelineSerializer
    ordering = ('name',)

    @action(methods=['post'], detail=True)
    def publish(self, request, pk=None):
        # ....
        pipeline = get_object_or_404(models.Pipeline, pk=pk)
        project_name = request.data['project_name']  # project name is part of the submission, not the url

```

The advantage of this approach is that the rest framework library takes care of the security and the permissions are inherited (so far we don't have any special concern here but who knows later), also you don't need to define a new entry in the `urlpatterns` list. The default url would be `/ui/pipelines/{id}/publish`.

2018-05-08 08:36 UTC, quesebifurcan commented on aether-ui/aether/ui/api/tests/__init__.py
> +}
This looks good, but could we reduce the size of this example a bit? It's a lot to read and scroll through when debugging. Simple example schema:

```
{
  "name": "Example",
  "type": "record",
  "fields": [
    {
      "name": "a",
      "type": "string"
    }
  ]
}
```

2018-05-08 08:38 UTC, lordmallam commented on aether-ui/aether/ui/api/views.py
> +def PublishPipeline(requests, pipelineid, projectname):
With the current implementation any method would suffice `GET` or `POST`, as it is simply to trigger the requests to the kernel. But i see sense in @obdulia-losantos's approach so i'll refactor to use a post

2018-05-08 08:51 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/tests/test_utils.py
> +        self.client.login(username=username, password=password)
I removed this line and the tests passed!!! This view is skipping authentication!!! :scream:

2018-05-08 08:54 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/views.py
> +def PublishPipeline(requests, pipelineid, projectname):
Regarding "safe" methods... 
http://www.django-rest-framework.org/api-guide/permissions/#api-reference

So far we only required authenticated users

https://github.com/eHealthAfrica/aether/blob/develop/aether-common-module/aether/common/conf/settings.py#L128

2018-05-08 09:51 UTC, quesebifurcan requested changes

2018-05-08 09:51 UTC, quesebifurcan commented on aether-ui/aether/ui/api/views.py
> +        return JsonResponse({'message': str(e), 'error': 'Bad request'}, status=400)
What happens if some of these calls fail but others succeed? My impression is that we will then end up with an invalid representation of the pipeline in the kernel database.

An alternative strategy would be to add a new (`POST`) view to kernel, which accepts a JSON doc representing an entire project (including schemas, projectschemas, mappings etc). This view can then be wrapped in `@transaction.atomic` to make sure that kernel is always consistent. See: https://docs.djangoproject.com/en/2.0/topics/db/transactions/#controlling-transactions-explicitly

2018-05-08 09:54 UTC, quesebifurcan commented on aether-ui/aether/ui/api/views.py
> +        return JsonResponse({'message': str(e), 'error': 'Bad request'}, status=400)
Example post data:
```
{
  "project_name": "test",
  "schemas": [...],
  "mappings": [...],
   ...etc.
}
```
Would be great to validate this with a schema while we're at it.

2018-05-08 10:27 UTC, lordmallam commented on aether-ui/aether/ui/api/views.py
> +        return JsonResponse({'message': str(e), 'error': 'Bad request'}, status=400)
The eventual result is to get the mappings saved to the kernel, which depends on the `project, schemas, and project_schemas` to be setup correctly. During the publish process a number of items can succeed while others fail. Handling of this scenario was skipped in this PR due to lack of clarity as to how the `ui` will handle the possible outcomes. An update with the logic to report happenings on the kernel will be pushed shortly

2018-05-08 10:29 UTC, lordmallam commented on aether-ui/aether/ui/api/views.py
> +        return JsonResponse({'message': str(e), 'error': 'Bad request'}, status=400)
Also, the aim is to leave the `kernel` as is and all logic concerning `ui` (pipelines) should be on the ui module

2018-05-08 10:30 UTC, quesebifurcan commented on aether-ui/aether/ui/api/views.py
> +        return JsonResponse({'message': str(e), 'error': 'Bad request'}, status=400)
That makes sense :+1:  We can discuss this further in the channel and/or standup. My main point was that handling these errors is much easier and less error prone if we do it in the kernel, so it would make sense for us to add a new endpoint for submitting a project in one swoop.

2018-05-09 11:47 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/tests/test_utils.py
> +        self.client.login(username=username, password=password)
Could you create a test without "login"? Just to check that anonymous users cannot break anything :crossed_fingers:

2018-05-09 11:49 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/tests/test_utils.py
> +        self.client.login(username=username, password=password)
Actually, login is not needed here but in view tests :grimacing:

2018-05-09 11:53 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/utils.py
> +def publishPipeline(requests, pipelineid, projectname):
The `requests` argument is not used at all and creates a little bit of confusion, could you take it out?

2018-05-09 11:59 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/views.py
> +        return ui_utils.publishPipeline(request, pk, project_name)
I would suggest to pass as an argument the `pipeline`, not the `pk`.

There is an specific method in Django that will throw a 404 error if the object does not exist. I think this is the expected error when you try to publish a non-existent pipeline :thinking: 

```python
from django.shortcuts import get_object_or_404

def .... (..., pk):
    pipeline = get_object_or_404(models.Pipeline, pk=pk)
    # ...
    return ui_utils.publishPipeline(pipeline, project_name)

```

2018-05-09 12:03 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/PipelineList.jsx
> +import { addPipeline, selectedPipelineChanged, getPipelines, publishPipeline } from './redux'
Is the `publishPipeline` used somewhere in this file? or are you going to include the button later?

2018-05-09 12:05 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/redux.spec.jsx
> +  it('should dispatch an publish pipeline action and save respose in the redux store', () => {
typo `respose` :wink:

2018-05-09 12:06 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/redux.spec.jsx
> +  it('should dispatch an publish pipeline action and save respose in the redux store', () => {
`dispatch AN publish` or `dispatch A publish` ?

2018-05-09 12:08 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/utils/api.jsx
> +                    resolve({ error, status: res.status })
`resolve` or `reject` ? :thinking: :flushed:

2018-05-09 12:09 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/redux.spec.jsx
> +  it('should dispatch a wrong publish pipeline action and save respose in the redux store', () => {
`respose`

2018-05-09 12:19 UTC, lordmallam commented on aether-ui/aether/ui/api/views.py
> +        return ui_utils.publishPipeline(request, pk, project_name)
There are a number of expected errors while publishing a pipeline, an invalid pipeline id being one. The `publishPipeline` utils function https://github.com/eHealthAfrica/aether/pull/151/files#diff-9ed92cc050ab97d135d3e96acaec24a6R195, I am just trying not to make extra branches on the view.

2018-05-09 12:19 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/utils.py
> +            return JsonResponse({'links': None, 'info': outcome}, status=400)
I wonder if it's better to return the `outcome` object in this method and let the `publish` viewset method to deal with the response and the statuses codes... but it's up to you.

2018-05-09 12:20 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/pipeline/PipelineList.jsx
> +import { addPipeline, selectedPipelineChanged, getPipelines, publishPipeline } from './redux'
Not yet... a publish is to be possible from the list as well, i'll take it out pending when the mockups are ready

2018-05-09 12:22 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/PipelineList.jsx
> +import { addPipeline, selectedPipelineChanged, getPipelines, publishPipeline } from './redux'
You can leave it there if you want, sooner or later is going to be there...

2018-05-09 12:23 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/views.py
> +        return ui_utils.publishPipeline(request, pk, project_name)
I can imagine that the list of unexpected errors is longer :joy:

2018-05-09 12:30 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/utils/api.jsx
> +                    resolve({ error, status: res.status })
Actually `resolve` ref: https://github.com/eHealthAfrica/aether/blob/aet-ui-push-to-kernel/aether-ui/aether/ui/assets/apps/redux/middleware/client.jsx#L16, an error on `res.json()` will then result in a `reject`

2018-05-09 12:44 UTC, lordmallam commented on aether-ui/aether/ui/api/utils.py
> +            return JsonResponse({'links': None, 'info': outcome}, status=400)
Not sure i understand that approach as to how to determine what the status code is on the viewset. The `outcome` object is built at different stages with different status per action performed on the kernel

2018-05-09 13:23 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/utils.py
> +            return JsonResponse({'links': None, 'info': outcome}, status=400)
Let me explain better but as I said before do whatever you want...

```python
# utils.py

def publishPipeline(pipelineid, projectname):
    '''
    Transform pipeline to kernel data and publish
    '''
    outcome = {
        'successful': [],
        'failed': [],
        'exists': []
    }

    # do magic....
    if error_somewhere:
        outcome['failed'].append('some reason')
        return outcome  # instead of JsonResponse

    return outcome

# ------------------------------------------------

# views.py


class PipelineViewSet(viewsets.ModelViewSet):
    queryset = models.Pipeline.objects.all()
    serializer_class = serializers.PipelineSerializer
    ordering = ('name',)

    @action(methods=['post'], detail=True)
    def publish(self, request, pk=None):
        '''
        This view transform the supplied pipeline to kernal models,
        publish and update the pipeline with related kernel model ids.
        '''
        project_name = request.data['project_name'] if 'project_name' in request.data else 'Aux'
        outcome = ui_utils.publishPipeline(pk, project_name)

        if not len(outcome['failed']) and not len(outcome['exists']):
            # somewhere pipeline = ...
            return Response(data=serializers.PipelineSerializer(pipeline, context={'request': request}).data)
        else:
            return Response(data=outcome, status=400)

```

2018-05-09 13:23 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/utils.py
> +def publishPipeline(pipelineid, projectname):
:D thanks!

2018-05-09 13:32 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/utils/api.jsx
> +                    resolve({ error, status: res.status })
What I meant is that the `resolve` is already done and here you are dealing with >= 400 status codes, so it should be `reject` because is an error in the server response.

2018-05-09 14:06 UTC, lordmallam commented on aether-ui/aether/ui/api/utils.py
> +            return JsonResponse({'links': None, 'info': outcome}, status=400)
I see.. Just for clarity, i am going with this method because from [L247](https://github.com/eHealthAfrica/aether/blob/aet-ui-push-to-kernel/aether-ui/aether/ui/api/utils.py#L247) to [L270](https://github.com/eHealthAfrica/aether/blob/aet-ui-push-to-kernel/aether-ui/aether/ui/api/utils.py#L270) `exists` or `failed` in the outcome object does not necessarily mean the request failed. I think making a selection when the required info is available to make that decision, should be made rather than deffering, especially in this case where a request is made up of multiple requests.

2018-05-09 14:09 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/utils.py
> +            return JsonResponse({'links': None, 'info': outcome}, status=400)
I took that line to make the difference between fail and success as I could have taken another one; but what it's better in your opinion it's going to be great.

2018-05-09 14:25 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/utils/api.jsx
> +                    resolve({ error, status: res.status })
Rejections have to be of `Error` Type, since this plugs into `redux` i need an object in the format it is to be sent as the failure payload. Note: a failure may come along with an object detailing the exact reason of failure on the server like in the `outcome` case, i need the user to have all that juicy info.

2018-05-09 14:38 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/utils/api.jsx
> +                    resolve({ error, status: res.status })
All requests go through the [middleware](https://github.com/eHealthAfrica/aether/blob/aet-ui-push-to-kernel/aether-ui/aether/ui/assets/apps/redux/middleware/client.jsx) where this concern is addressed

2018-05-15 09:15 UTC, quesebifurcan requested changes

2018-05-15 09:15 UTC, quesebifurcan commented on aether-ui/aether/ui/api/models.py
> +    kernel_refs = JSONField(blank=True, null=True, editable=False)
Is there any validation of the data which can go into this field? Since other parts of the program depend on it conforming to a certain structure, it would be great to have something there.

2018-05-15 09:15 UTC, quesebifurcan commented on aether-ui/aether/ui/api/tests/test_utils.py
> +                     create_project_schema_object)
An alternative to these long tuples would be to `from .. import utils` and then call the functions like `utils.kernel_data_request()`. Not necessary to fix right now, just mentioning it.

2018-05-15 09:15 UTC, quesebifurcan commented on aether-ui/aether/ui/api/tests/test_utils.py
> +          name=PIPELINE_EXAMPLE_1['name'],
You might want to check the indentation here (should be 4 spaces). I'm surprised the linter doesn't complain :smile:

2018-05-15 09:15 UTC, quesebifurcan commented on aether-ui/aether/ui/api/tests/__init__.py
> +}
Alright, 500 lines is less than 800 lines, but it would be wonderful to have shorter test data. We might need to add to/alter the schemas sooner rather than later.

2018-05-15 09:15 UTC, quesebifurcan commented on aether-ui/aether/ui/api/utils.py
> +def publishPipeline(pipelineid, projectname):
Minor thing -- all functions should use snake case: `publish_pipeline`

2018-05-15 11:31 UTC, lordmallam commented on aether-ui/aether/ui/api/models.py
> +    kernel_refs = JSONField(blank=True, null=True, editable=False)
There is no validation. The field is used to store links to kernel objects, if a ref to a certain object isn't in the dict it is not linked. keys to an object are only added once the object has been created on the kernel

2018-05-15 13:36 UTC, quesebifurcan approved these changes
:+1: Nice work!

We can merge this now, but I think it's important to keep track of and eventually address a couple of issues:
- validation of `kernel_refs`
- interaction with kernel -- it's currently more complicated than it has to be. I would suggest extending the kernel API with views which are helpful for building the UI (among other things, that would allow us to use transactions when registering pipeline objects).

2018-05-15 14:10 UTC, merged