feat: (ui) input and entity types mapping indicator
eHealthAfrica/aether pull request #152
Opened 2018-05-04 15:14 UTC by lordmallam

Indicates which properties have been mapped on `input` and `entity types`

#### Related JIRA ticket
[AET-230](https://jira.ehealthafrica.org/browse/AET-230)

#### To be styled

2018-05-08 08:09 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Mapping.jsx
> +    if (nextProps.selectedPipeline.mapping !== this.props.selectedPipeline.mapping) {
I found out that this line is most of the time true when it shouldn't (pointers and immutability) so it's better to use the `deepEqual` method that checks content not pointers.

`if (!deeptEqual(nextProps.selectedPipeline.mapping, this.props.selectedPipeline.mapping)) {`

2018-05-08 08:32 UTC, obdulia-losantos commented
In the input side, shouldn't the rest of fields in the mapping rules be bold as the entity type ones are?

![image](https://user-images.githubusercontent.com/8459537/39746552-edfeb79c-52aa-11e8-9083-1edfae8aee39.png)

2018-05-08 08:36 UTC, sabeen commented
you mean that _forename_ etc. should also have a background, like the __id_?
Yes, it should.

2018-05-08 08:39 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Mapping.jsx
> +  setMappingStyles () {
I found this approach so "jquery" approach and we are using "react" that can take care of this in a better way :thinking: 

Maybe in the render method...

```javascript
// EntityTypeViewer.jsx

// before
// result.push(<li key={field.name}><span className='name'>{field.name}</span> ... )

// possible solution
result.push(
  <li key={field.name} className={ (field in any mapping rule) ? 'entityType-mapped' : '' }>
    <span className='name'>{field.name}</span>
  // ...
)

```

2018-05-14 09:28 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +    console.log(this.props.selectedPipeline)
Oops!

2018-05-14 09:30 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/tests/ui-tests-environment/UiTestsEnvironment.jsx
> +    this.global.HTMLElement = this.global.window.HTMLElement
I forgot to remove this line :man_facepalming:

2018-05-14 09:35 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/css/base/_color-codes.scss
> +.input-mapped {
Should this one be the `.input-mapped-0`? (this happens when the input schema entry is in a rule but the Entity type is missing)

2018-05-14 12:08 UTC, lordmallam commented on aether-ui/aether/ui/assets/css/base/_color-codes.scss
> +.input-mapped {
Is that supposed to be allowed? to have a mapping with a source but without a destination?

2018-05-14 12:12 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/css/base/_color-codes.scss
> +.input-mapped {
No, but you can have it with a wrong destination ;-)

rule:
 - source: `participant.firstName`
 - destination: `persson.name` (wrong)

Entity types:
 - Person
 - Participant
 - ...

2018-05-14 12:53 UTC, lordmallam commented on aether-ui/aether/ui/assets/css/base/_color-codes.scss
> +.input-mapped {
If that happens, the property on entity type will not be highlighted, there should only be an error highlight on the mapping textbox (destination)

2018-05-14 14:14 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/css/base/_color-codes.scss
> +.input-mapped {
In that case, I think you can safely remove this entry.

2018-05-14 15:24 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/css/base/_color-codes.scss
> -}
:+1:

2018-05-15 09:21 UTC, quesebifurcan requested changes

2018-05-15 09:21 UTC, quesebifurcan commented on aether-ui/aether/ui/assets/apps/components/AvroSchemaViewer.jsx
> +    // the simplest way (equity)
Spelling: "equity" -> "equality"?

2018-05-15 09:21 UTC, quesebifurcan commented on aether-ui/aether/ui/assets/apps/components/AvroSchemaViewer.jsx
> +  schemaToMarkup (schema, parent) {
Perhaps add a comment about the type of `parent` in this context? 
Is it a string? If so, where does it come from? Can it be `null`?

2018-05-15 09:21 UTC, quesebifurcan commented on aether-ui/aether/ui/assets/apps/mock/schema_input.mock.jsx
> +        'doc': 'Type inferred from “1972”'
I think this can be removed -- it's just a leftover from when this schema was derived.

2018-05-15 13:36 UTC, quesebifurcan approved these changes

2018-05-15 13:51 UTC, merged