Aet ui load mappings from kernel
eHealthAfrica/aether pull request #167
Opened 2018-05-15 15:37 UTC by lordmallam

Fetch mapping data from the `kernel` and transform and store as `ui pipelines`
NOTE: 

- Pipeline input data and schema defaults to `{}`
- Subsequent mapping updates from the kernel are not effected to prevent overwriting changes on the ui.

#### How to test

- Setup kernel with project, schema, project schema and mappings
- Load ui
- A pipeline should be added to the pipeline list reflecting the mappings on kernel

2018-05-16 12:56 UTC, quesebifurcan commented
I'm currently not able to update kernel mappings or schemas. After

1. creating a pipeline
2. publishing the pipeline
3. editing the mapping and entity types
4. publishing the pipeline (again)

...kernel is still in a state which corresponds to step 2. Any ideas? @lordmallam

2018-05-16 13:56 UTC, lordmallam commented
@quesebifurcan as stated in this [PR](https://github.com/eHealthAfrica/aether/pull/151), updates to kernel objects created from a pipeline by republishing is to be determined by whether the user wants to overwrite existing kernel objects (schemas and mappings) or create new ones with new names. Thus, the dependence on [AET-254](https://jira.ehealthafrica.org/browse/AET-254)

2018-05-16 16:34 UTC, tooxie commented on aether-ui/aether/ui/api/utils.py
> +                    'name': pipeline.name,
Isn't it risky to change this? Couldn't we end up with 2 different naming schemas in the same DB?

2018-05-17 08:13 UTC, lordmallam commented on aether-ui/aether/ui/api/utils.py
> +                    'name': pipeline.name,
As it is not in production yet, I don't think it is a concern. BTW, the change was made to match the pipeline naming on the ui to that of the kernel mapping being that the end product of a pipeline is a mapping

2018-05-18 10:54 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/utils.py
> +    return result
The pythonic way of life...

```python
    return [
        {'source': mapping[0], 'destination': mapping[1]}
        for mapping in mapping_from_kernel
    ]
```

2018-05-18 10:59 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/views.py
> +        return JsonResponse(serialized_data, status=200, safe=False)
You don't need to use `JsonResponse`, rest framework is going to transform it into JSON because the default parser is the JsonParser.

On the other hand this should not be a `GET` method because you are adding data from Kernel, and any method that creates/transforms/deletes data is not safe at all. I think it's better `POST`.

Safe methods are `HEAD`, `OPTIONS` and `GET`.

2018-05-22 09:18 UTC, quesebifurcan requested changes

2018-05-22 09:18 UTC, quesebifurcan commented on aether-kernel/aether/kernel/api/views.py
> +
We might have what you're looking for already, implemented in `filters.py` for all models.

If you try (on develop):
```
curl http://kernel.aether.local:8000/projects/?name=AUX
```
Is that what you need?

2018-05-22 09:18 UTC, quesebifurcan commented on aether-ui/aether/ui/api/utils.py
> +            pass
I think we need to handle any errors here and not just let them pass through. If you expect `KeyError`s in the lookups, you could (for example) handle those explicitly. `except Exception` catches everything, including typos.

2018-05-22 09:18 UTC, quesebifurcan commented on aether-ui/aether/ui/api/tests/test_utils.py
> +            self.assertEqual(exception['object_name'], 'unknown')
Could we add a test for the success case as well?

2018-05-22 09:18 UTC, quesebifurcan commented on aether-ui/aether/ui/api/tests/test_views.py
> +    def test_view_02_pubish_pipeline(self):
Could we avoid using numbers in function here? `test_publish_pipeline` would be enough. Numbers are tricky to maintain -- what if we move tests around or want to add a new inbetween 2 and 3?

2018-05-22 09:18 UTC, quesebifurcan commented on aether-kernel/aether/kernel/api/views.py
> +
(Same as above)

2018-05-22 17:47 UTC, lordmallam commented on aether-ui/aether/ui/api/tests/test_utils.py
> +            self.assertEqual(exception['object_name'], 'unknown')
Success case test can be found [here](https://github.com/eHealthAfrica/aether/pull/167/files#diff-a6f7f46e059290d2c7ee9e3cc99bb4deR425)

2018-05-23 14:56 UTC, quesebifurcan requested changes

2018-05-23 14:56 UTC, quesebifurcan commented on aether-kernel/aether/kernel/api/utils.py
> +    return queryset.filter(name=name)
Do we still need this? Looks like it was only used by the `byname` methods you removed.

2018-05-23 14:56 UTC, quesebifurcan commented on aether-ui/aether/ui/api/utils.py
> +        raise Exception(e)
I think this could be simplified to `kernel_data_request(f'{object_name.lower()}s/{id}/', 'put', data)` -- the exception is just caught and immediately reraised. Also, it's always nice to get the return value (especially the status code) from a function using `requests`.

2018-05-23 14:56 UTC, quesebifurcan commented on aether-ui/aether/ui/api/utils.py
> +def publish_preflight(pipeline, project_name, outcome):
This is a rather long function -- could you add a docstring which briefly outlines what it's supposed to do?

2018-05-23 14:56 UTC, quesebifurcan commented on aether-ui/aether/ui/api/utils.py
> +        project_schema = kernel_data_request(f'projectschemas/{entities_from_kernel[entity]}/')
Could you try `for entity, entity_id in entities_from_kernel.items()`?
Then we could avoid the dictionary lookups inside the format strings.

2018-05-23 14:56 UTC, quesebifurcan commented on aether-ui/aether/ui/api/utils.py
> +            create_new_pipeline_from_kernel(mapping)
Could we make sure that every function returns a value? Otherwise, they can become quite difficult to debug.

2018-05-23 16:08 UTC, tooxie commented on aether-ui/aether/ui/api/views.py
> +        serialized_data = serializers.PipelineSerializer(pipelines, context={'request': request}, many=True).data
Is there any possible exception being thrown by this?

2018-05-23 16:08 UTC, tooxie commented on aether-ui/aether/ui/api/views.py
> +        ui_utils.kernel_to_pipeline()
This can raise [a couple of exceptions](https://github.com/eHealthAfrica/aether/blob/aet-ui-load-mappings-from-kernel/aether-ui/aether/ui/api/utils.py#L128-L136) that are not being handled anywhere.

2018-05-23 16:08 UTC, tooxie commented on aether-ui/aether/ui/api/views.py
> +            pipeline = get_object_or_404(models.Pipeline, pk=pk)
Looks like you are ignoring the `_or_404` part of the shortcut. Why don't you use `models.Pipeline.get()` instead which will raise a `DoesNotExist` exception if the object is not found?

2018-05-23 16:08 UTC, tooxie commented on aether-ui/aether/ui/api/views.py
> +        if len(outcome['exists']):
An empty list evals as `False` in python, you don't need to call `len()`.

2018-05-23 16:08 UTC, tooxie commented on aether-ui/aether/ui/api/views.py
> +            if overwrite:
What is being overwritten here?

2018-05-23 16:08 UTC, tooxie commented on aether-ui/aether/ui/api/views.py
> +            outcome = ui_utils.publish_pipeline(pipeline, project_name)
This call is almost identical to line 53's. Would it be possible to refactor this to prevent this code duplication?

2018-05-23 16:08 UTC, tooxie commented on aether-ui/aether/ui/api/views.py
> +        overwrite = False
TBH I find this code very hard to follow. What I think could be changed:
* There are 4 return calls in 15 lines (3 of those are `return Response(outcome, status=HTTPStatus.BAD_REQUEST)`)
* `outcome['error']` gets written and deleted at the end. Maybe not add it unless necessary?
* too many `if/else` branches
* almost no error handling

I think it would help if we could flatten the code.

2018-05-23 16:08 UTC, tooxie commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +    // todo: check if and overwrite is required
How do we make sure this doesn't get overlooked and forgotten? Would it be possible to create a jira ticket instead?

2018-05-23 16:08 UTC, tooxie commented on aether-ui/aether/ui/assets/apps/pipeline/PipelineList.jsx
> +    this.props.fetchPipelines()
No semicolons? 🤔

2018-05-23 16:08 UTC, tooxie commented on aether-ui/aether/ui/assets/apps/pipeline/redux.jsx
> +    `${urls.PIPELINES_URL}fetch/?limit=5000`,
Why 5000?

2018-05-23 16:08 UTC, tooxie commented on aether-ui/aether/ui/assets/apps/pipeline/redux.jsx
> +      return { ...state, publishError: action.error.error }
Why did `action.error` became `action.error.error`? I don't see that being used anywhere else.

2018-05-23 16:08 UTC, tooxie commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Output.jsx
> +  buildPublishSuccess (success) {
Just `success` is a misleading name for a list, sounds like a boolean. What about `publishedPipelines` for example?

2018-05-23 16:08 UTC, tooxie commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Output.jsx
> +    return <ul>{successList}</ul>
IMHO it would be more idiomatic to reduce the list instead:
```js
buildPublishSuccess (publishedPipelines) {
  const formattedMessages = publishedPipelines.reduce((formattedList, pipe) => {
    return (
      <li key=pipe>
        <FormattedMessage id={`publish.success.${pipe}`} defaultMessage={pipe} />
      </li>
    );
  });

  return <ul>{formattedMessages}</ul>;
}
```

And you don't really need the `formattedMessages` throwaway list actually.

2018-05-23 16:08 UTC, tooxie commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Output.jsx
> +          this.props.publishError && (
IMHO this is a misuse of a binary operator, and makes the code harder to read. I think that you could move that to a function instead:
```js
const getErrors = (errors) => {
  if (errors) {
    return <div className='pipeline-errors'> ... </div>
  }
}

render() {
  return (
    <div className='section-body'>
      {
        getErrors(this.props.publishError);
        getFormattedMessages(this.props.publishSuccess);
      }
    </div>
  );
}
```

2018-05-23 16:44 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +    // todo: check if and overwrite is required
This is implemented [here](https://github.com/eHealthAfrica/aether/blob/aet-ui-publish-actions/aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx#L130) comment to be removed. PR coming soon

2018-05-23 16:45 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/pipeline/PipelineList.jsx
> +    this.props.fetchPipelines()
Nope.. 😉

2018-05-23 16:46 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/pipeline/redux.jsx
> +    `${urls.PIPELINES_URL}fetch/?limit=5000`,
Just to make sure all records are returned.. pagination not fully in place

2018-05-23 17:01 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Output.jsx
> +          this.props.publishError && (
`short-circuit operators` `&&` doesn’t evaluate the right-hand side expression, if just by evaluating the left-hand expression can decide the final result.

2018-05-23 17:05 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/pipeline/redux.jsx
> +      return { ...state, publishError: action.error.error }
Because of the `error` object from [here](https://github.com/eHealthAfrica/aether/pull/167#discussion_r190297524)

2018-05-23 17:15 UTC, lordmallam commented on aether-ui/aether/ui/api/views.py
> +            outcome = ui_utils.publish_pipeline(pipeline, project_name)
same function is called with a different arg. What refactor suggestions do you have?

2018-05-23 17:17 UTC, lordmallam commented on aether-ui/aether/ui/api/views.py
> +            if overwrite:
Objects in the kernel db

2018-05-23 17:25 UTC, lordmallam commented on aether-ui/aether/ui/api/views.py
> +            pipeline = get_object_or_404(models.Pipeline, pk=pk)
`_or_404` raises a `Http404` exception which is noted in `L48`. I agree a simpler message can suffice

2018-05-23 17:54 UTC, lordmallam commented on aether-ui/aether/ui/api/views.py
> +        overwrite = False
the logic implemented covers the possible outcome from a pipeline publish. All errors/exceptions and successes are logged in the `outcome` dict and handled on a conditional bases.

Torn between maintaining the `outcome['error']` list in one function or having to check if the list is exists or not before declaration (not to overwrite existing entries),  and adding to it in multiple places. I went for managing it in one place.

2018-05-24 07:41 UTC, quesebifurcan approved these changes

2018-05-24 07:43 UTC, quesebifurcan commented
Looks good :+1: let's get @tooxie 's suggestions in here as well and then I think it'll be good to go.

2018-05-24 08:12 UTC, tooxie commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Output.jsx
> +    return <ul>{successList}</ul>
Now that I think about it, we are going through all published pipelines, so a `map` is better suited for this.

2018-05-24 08:13 UTC, tooxie commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Output.jsx
> +          this.props.publishError && (
You are right, and it works, but my concern is more about readability of the code.

2018-05-24 08:19 UTC, tooxie commented on aether-ui/aether/ui/api/views.py
> +            pipeline = get_object_or_404(models.Pipeline, pk=pk)
It's not about simplicity imo, but about using `get_object_or_404` just to test existence of an object. The function is not returning 404 (as I expected when I saw the `get_objects_or_404` call) but 400 instead. So I think it's more suitable to test explicitly for the existence of the object because it explains the purpose of the code.

2018-05-24 08:56 UTC, tooxie commented on aether-ui/aether/ui/api/views.py
> +            outcome = ui_utils.publish_pipeline(pipeline, project_name)
This would be my suggestion:
```py
class BadRequestResponse(Response):
    def __init__(self, error=None, outcome=None):
        if not outcome:
            outcome = {
                'successful': [],
                'error': [],
                'exists': [],
            }

        if error:
            outcome['error'].append(error)

        super(BadRequestResponse, self).__init(outcome, status=HTTPStatus.BAD_REQUEST)


class PipelineViewSet(viewsets.ModelViewSet):
    @action(methods=['post'], detail=True)
    def publish(self, request, pk=None):
        '''
        This view transform the supplied pipeline to kernel models,
        publish and update the pipeline with related kernel model ids.
        '''
        project_name = request.data.get('project_name', 'Aux')
        overwrite = request.data.get('overwrite', False)
        outcome = {}

        try:
            pipeline = models.Pipeline.get(pk=pk)
        except DoesNotExist as error:
            return BadRequestResponse(error=error)

        outcome = ui_utils.publish_preflight(pipeline, project_name, outcome)
        if outcome['exists'] and not overwrite:
            return BadRequestResponse(outcome=outcome)
        else:
            outcome = ui_utils.publish_pipeline(pipeline, project_name, overwrite)

        if outcome['error']:
            return BadRequestResponse(outcome=outcome)

        return Response(outcome, status=HTTPStatus.OK)
```

I'm not sure this code works, I haven't tried it, but it's just to give you an idea. I abstracted all the responses into its own class to make it clear which return statements are errors and which are `OK`.

It also flattens the couple of nested ifs by combining them into `if outcome['exists'] and not overwrite`. Please triple check that this expression is correct, I'm terrible at boolean logic :)

And I left the final `return` at the end, outside of any if branch, to make it visually clear that this function cannot return `undefined`.

Again, this is just an idea, treat it as pseudo code :)

2018-05-24 09:00 UTC, lordmallam commented on aether-ui/aether/ui/api/views.py
> +            pipeline = get_object_or_404(models.Pipeline, pk=pk)
I understand. Here's the discussion on how we got here https://github.com/eHealthAfrica/aether/pull/151/files/c903d82cad16ef6b913b1cf96cbbf059c6b1c7b0#r187016024

2018-05-24 09:27 UTC, lordmallam commented on aether-ui/aether/ui/api/views.py
> +            outcome = ui_utils.publish_pipeline(pipeline, project_name)
Nice. I like the `BadRequestResponse` abstraction. Due to current usage of the `outcome` variable in especially the `/utils` file, i will look into the refactor in another PR

2018-05-24 09:32 UTC, tooxie commented on aether-ui/aether/ui/api/views.py
> +            pipeline = get_object_or_404(models.Pipeline, pk=pk)
I see. The difference, if I understand it correctly, is that in the case you mention the function actually returns a 404 if the object doesn't exist. In this case however, we return 400. Is that correct?

2018-05-24 09:52 UTC, merged