feat(odk): parse xForm into to AVRO schema
eHealthAfrica/aether pull request #170
Opened 2018-05-17 16:39 UTC by obdulia-losantos

https://jira.ehealthafrica.org/browse/AET-246

- Reorganized code.
- Use `pyxform` methods when possible instead of handmade ones.
- Include more use cases in the samples, like empty geopoints, empty arrays, nested arrays (Thanks to @quesebifurcan ), default values and multilanguage.
- Improve the xForm validation method.
- Generate AVRO schema from xForm definition and save in the database.

Assumptions:
- `pyxform` methods work as expected (like `XFormInstanceParser`).
- The instance skeleton is included in the xForm definition (the only `instance` tag without id). The survey fields appear in order.
- ODK collect will send back the whole skeleton with null values if needed. This means that only leafs can be null.

2018-05-22 08:58 UTC, quesebifurcan commented
Looks great! As mentioned, I ran into some issues with nested repeats. Pushed an example here: https://github.com/eHealthAfrica/aether/commit/f11b4b8834c022710d22b94e4eacff01ac975e50

Current output of nested repeats:
```
...
{
      "name": "Repeat_1",
      "doc": null,
      "type": {
        "type": "array",
        "items": {
          "name": "Repeat_1",
          "doc": null,
          "type": "record",
          "fields": [
            {
              "name": "name",
              "type": [
                "null",
                "string"
              ],
              "doc": "name_label"
            },
            {
              "name": "Repeat_2",
              "doc": null,
              "type": "record",
              "fields": [
                {
                  "name": "name2",
                  "type": [
                    "null",
                    "string"
                  ],
                  "doc": "name_label"
                }
              ]
            }
          ]
        }
      }
    },
...
```

2018-05-22 09:00 UTC, obdulia-losantos commented
Looking into it, thanks for finding this!

2018-05-22 09:17 UTC, obdulia-losantos commented
@quesebifurcan better?

```json
{
  "name": "NestedRepeatsTest",
  "namespace": "aether.odk.xforms",
  "doc": "nested repeats test (id: nested_repeats_test, version: 0)",
  "type": "record",
  "fields": [
    {
      "name": "_id",
      "doc": "xForm ID",
      "type": "string",
      "default": "nested_repeats_test"
    },
    {
      "name": "_version",
      "doc": "xForm version",
      "type": "string",
      "default": "0"
    },
    {
      "name": "Repeat_1",
      "type": {
        "type": "array",
        "items": {
          "name": "Repeat_1",
          "doc": null,
          "type": "record",
          "fields": [
            {
              "name": "name",
              "type": [
                "null",
                "string"
              ],
              "doc": "name_label"
            },
            {
              "name": "Repeat_2",
              "type": {
                "type": "array",
                "items": {
                  "name": "Repeat_2",
                  "doc": null,
                  "type": "record",
                  "fields": [
                    {
                      "name": "name2",
                      "type": [
                        "null",
                        "string"
                      ],
                      "doc": "name_label"
                    }
                  ]
                }
              }
            }
          ]
        }
      }
    },
    {
      "name": "meta",
      "type": {
        "name": "meta",
        "doc": "/meta",
        "type": "record",
        "fields": [
          {
            "name": "instanceID",
            "type": [
              "null",
              "string"
            ],
            "doc": "/meta/instanceID"
          }
        ]
      }
    }
  ]
}
```

2018-05-22 09:26 UTC, quesebifurcan commented
@obdulia-losantos looks good!

I tried generating a value for your new schema, the output makes sense to me.
```
{
  "_id": "rhEZDCKCxjRhdUnWCZkOFt",
  "_version": "GJR",
  "Repeat_1": [
    {
      "name": "DEzwKXHrOktBXcMEzzmtMyPDy",
      "Repeat_2": [
        {
          "name2": "BqIfWMwDzrsAhhSNBJfQdZLPcYLrzp"
        },
        {
          "name2": null
        },
        {
          "name2": null
        }
      ]
    }
  ],
  "meta": {
    "instanceID": "BWXbtZwZqWahghCUWyj"
  }
}
```

2018-05-22 09:47 UTC, quesebifurcan commented
@obdulia-losantos Looking at groups, the following xform doesn't result in a valid avro schema, as far as I can tell:

```
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:odk="http://www.opendatakit.org/xforms" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>cascading select test</h:title>
    <model>
      <instance>
        <groups id="cascading_select_test">
          <group1>
            <name/>
          </group1>
          <meta>
            <instanceID/>
          </meta>
        </groups>
      </instance>
      <bind nodeset="/groups/group1/name" type="string"/>
      <bind calculate="concat('uuid:', uuid())" nodeset="/groups/meta/instanceID" readonly="true()" type="string"/>
    </model>
  </h:head>
  <h:body class="pages">
    <group ref="/groups/group1">
      <label>group1_label</label>
      <input ref="/groups/group1/name">
        <label>name_label</label>
      </input>
    </group>
  </h:body>
</h:html>
```
Output from `parse_xform_to_avro_schema`:
```
var schema = {
  "name": "CascadingSelectTest",
  "doc": "cascading select test (id: cascading_select_test, version: 0)",
  "type": "record",
  "fields": [
    {
      "name": "_id",
      "doc": "xForm ID",
      "type": "string",
      "default": "cascading_select_test"
    },
    {
      "name": "_version",
      "doc": "xForm version",
      "type": "string",
      "default": "0"
    },
    {
      "name": "group1",
      "doc": "group1_label",
      "type": "record",
      "fields": [
        {
          "name": "name",
          "type": [
            "null",
            "string"
          ],
          "doc": "name_label"
        }
      ]
    },
    {
      "name": "meta",
      "doc": "/meta",
      "type": "record",
      "fields": [
        {
          "name": "instanceID",
          "type": [
            "null",
            "string"
          ],
          "doc": "/meta/instanceID"
        }
      ]
    }
  ]
}
```
I think the issue is that the field "group_1" has the type "record", whereas it should be `"type": {"type": "record"...etc.`

UPDATE: fixed in https://github.com/eHealthAfrica/aether/pull/170/commits/58dc4acbeab10e14f7c26bd6f353c60aa4599f1c

2018-05-22 15:39 UTC, obdulia-losantos commented
@quesebifurcan I think that I concluded with the changes.

Validation is included but because we know that is not 100% reliable in `spavro` I created our own `validate names` method in the meantime.

2018-05-23 08:18 UTC, shawnsarwar submitted a review, later dismissed
Looks great! My only suggestion is that we find a way to package the XForm -> Avro functionality and package it for PyPi as I think it's generally useful.

2018-05-23 10:25 UTC, quesebifurcan requested changes

2018-05-23 10:25 UTC, quesebifurcan commented on aether-odk-module/aether/odk/api/xform_utils.py
> +    raise TypeError('missing instance definition')
Maybe this would be a good place for an application-specific error? TypeError is very general, I'd expect to see that raised when python-related issues happen, such as `int({})`. And this is more related to the shape/content of the xml, if I'm not mistaken. 

Also, could we raise the new error inside the `Exception` block?
```
except KeyError:
    raise MissingInstanceError('...')
```

2018-05-23 10:25 UTC, quesebifurcan commented on aether-odk-module/aether/odk/api/xform_utils.py
> +        pass
Same thing here -- `except Exception: pass` is bit dangerous -- if any programming errors or typos sneak in, the result will always be an empty dict.

2018-05-23 10:25 UTC, quesebifurcan commented on aether-odk-module/aether/odk/api/xform_utils.py
> +        pass
And here :-)

2018-05-23 14:29 UTC, obdulia-losantos commented
@quesebifurcan fixed! :+1:

2018-05-23 14:35 UTC, quesebifurcan commented on aether-odk-module/aether/odk/api/models.py
> +'''
Beautiful!

2018-05-23 14:36 UTC, quesebifurcan approved these changes
Great work!

2018-05-23 14:46 UTC, merged