feat(odk): improve data model
eHealthAfrica/aether pull request #177
Opened 2018-05-25 09:55 UTC by obdulia-losantos

Changed:

In ODK module:
- renamed model `Mapping` to `Project`.
- added new field `kernel_id` in `XForm` model to keep track of the linked instances in Kernel.
- added replication methods from ODK to Kernel with default values.
- in view submission indicate missing instance ID ASAP, try to avoid useless db searching if possible.
- PATCH endpoint `{model}/{pk}/propagates` for projects and xforms.

Chore:
- adapted tests scripts, odk module does not need previous data in kernel.

https://docs.google.com/document/d/1wXVFfpWtDWeWSJiygx4GGdv6tOEX5wRTQMNdefnL6H0/edit

2018-05-25 14:16 UTC, obdulia-losantos commented
Open questions: 
- should we try to replicate every time a project or xform is created/updated?
- should we delete the kernel copies if the instance is deleted in odk?

2018-05-25 14:58 UTC, admbtlr requested changes

2018-05-25 14:58 UTC, admbtlr commented on aether-odk-module/aether/odk/api/kernel_replication.py
> +def replicate_project(project):
I'm not sure that `replicate` is the right term here. It's a little confusing, because it implies an exact copy, which is not really true. Maybe `create_kernel_project`?

2018-05-25 14:58 UTC, admbtlr commented on aether-odk-module/aether/odk/api/kernel_replication.py
> +def replicate_xform(xform):
`create_kernel_artefacts`?

2018-05-25 14:58 UTC, admbtlr commented on aether-odk-module/aether/odk/api/kernel_replication.py
> +class KernelReplicationError(Exception):
`KernelPropagationError`?

2018-05-28 04:49 UTC, quesebifurcan requested changes

2018-05-28 04:49 UTC, quesebifurcan commented on aether-odk-module/aether/odk/api/kernel_replication.py
> +def __upsert_item(item_model, item_id, item_new, item_update=None):
This method would be very useful for other modules (for example, I saw a lot of similar things in the `aether-ui` module recently). What do you think about adding this method to `kernel` instead? That would allow us to have the actual upsert logic run closer to the database.The odk-specific error handling would stay here, of course.

2018-05-28 04:49 UTC, quesebifurcan commented on aether-odk-module/aether/odk/api/views.py
> +        except KernelReplicationError as kre:
Just some thoughts: what happens if one of the kernel requests fails but the others succeed? Is there a risk that we end up with e.g. `mapping` and `projectschema` but no `schema`? If so, how do we recover from such errors?

An alternative would be to add a post view in kernel which attempts to create/update a project from request data like:
```
{"mapping": {...}, "schema": {...}, "projectschema":{...}}
```
...and wrap that view in a transaction, so the entire thing would roll back if e.g. the schema wasn't valid AVRO.

2018-05-28 08:47 UTC, obdulia-losantos commented on aether-odk-module/aether/odk/api/kernel_replication.py
> +def __upsert_item(item_model, item_id, item_new, item_update=None):
:thinking:

2018-05-28 08:49 UTC, obdulia-losantos commented on aether-odk-module/aether/odk/api/views.py
> +        except KernelReplicationError as kre:
I see this method being used by the UI publish feature :stuck_out_tongue: 

So, should we create an standard one that can be used by both systems? later even more apps ;-)

2018-05-28 08:52 UTC, quesebifurcan commented on aether-odk-module/aether/odk/api/views.py
> +        except KernelReplicationError as kre:
Precisely :smile: I think it would be helpful for every non-trivial aether module.

2018-05-28 09:48 UTC, obdulia-losantos commented on aether-odk-module/aether/odk/api/views.py
> +        except KernelReplicationError as kre:
If you don't mind I would rather prefer to do it in another PR and afterwards use that in this one... it's going to be clearer for everybody at the end. What do you think? :thinking:

2018-05-28 09:55 UTC, quesebifurcan commented on aether-odk-module/aether/odk/api/views.py
> +        except KernelReplicationError as kre:
Sure, that's fine with me :-) Maybe create a ticket so we remember to do it?

2018-05-29 13:53 UTC, obdulia-losantos commented on aether-odk-module/aether/odk/api/views.py
> +        except KernelReplicationError as kre:
Done in #180

2018-05-30 08:41 UTC, obdulia-losantos commented
@quesebifurcan now looks much simpler :wink:

2018-05-30 09:41 UTC, admbtlr approved these changes

2018-05-30 09:43 UTC, quesebifurcan approved these changes

2018-05-30 09:53 UTC, merged