Aet ui setup
eHealthAfrica/aether pull request #185
Opened 2018-05-30 15:32 UTC by lordmallam

UI ==> Develop

2018-05-31 13:44 UTC, obdulia-losantos requested changes
**OMG!!!** :tada:  @lordmallam **A W E S O M E**

As I said, I'm not the person for this task. 

Most of these comments appear now and not during the develop process because now it's when we have a global vision of the app. They can be taken into consideration or even skipped, because they are just that, comments not blockers.

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/utils.py
> +def convertMappings(mapping_from_kernel):
shouldn't this be `snake_case`? :snake:

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/utils.py
> +def convertEntityTypes(entities_from_kernel):
shouldn't this be `snake_case`? :snake:

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/components/PublishButton.jsx
> +import React, { Component } from 'react'
I don't see this as a common component that can be reused outside this app... this is so pipeline related that I would move it within the rest of pipeline files.

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/components/index.jsx
> +}
Being evil again :smiling_imp: 

It's good practice with this kind of files to have the list in alphabetical order. I know that now there are less than 10 files but still searching for a component is faster if they are in order.

In the imports and in the exports.

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/mock/index.jsx
> +}
Because they are only used in tests I would move the `mock` folder them into the `test` folder...

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/utils/constants.jsx
> +export const UI_APP = 'ui'
Are we using any of these constants? Or are part of the gather legacy?

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/utils/errors.jsx
> +export { BadRequestError, UnauthorizedError, NotFoundError, ConflictError }
Do we need all of them? So far we are only using `NotFoundError`

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/utils/index.jsx
> +  return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4()
This line makes me laugh every time I see it :joy:

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/conf/check_vars.sh
> +    echo "$2 in Ordnung!"
I'm still waiting for someone complaining about this line :de:

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/package-lock.json
> +{
Is this file necessary?

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/api/views.py
> +        project_name = request.data['project_name'] if 'project_name' in request.data else 'Aux'
after writing thousands of lines like this one I realized that the short way of writing this is `project_name = request.data.get('project_name', 'Aux')`

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/apps.py
> +    verbose_name = 'Aether Kernel UI'
Always wondering why this is named *Aether Kernel UI* `aether.ui` and not *Aether Kernel Pipeline* `aether.kernel.pipeline` :thinking:

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/README.md
> +* **Comments are warmly welcome!!!**
...but never read :smiling_imp:

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/components/AvroSchemaViewer.jsx
> +    } else if (typeof schema.type !== 'string') {
There is a ticket in Jira related to this line when the schema type is a union of types :see_no_evil: 

https://jira.ehealthafrica.org/browse/AET-264

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/components/EntityTypeViewer.spec.jsx
> +    // TODO: Updates when styles are added to rendered components
is this comment still a thing?

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/mock/pipelines.mock.jsx
> +const mockPipelines = {
Wondering if these files need to be javascript files and not simple json files :thinking: 

```json
{
  "results": [
    {
      "id": 1,
      "name": "Pipeline Mock 1",
      "mapping_errors": null,
      "mapping": [],
      "output": null,
      "entity_types": [],
      "schema": null,
      "input": null
    },
    {
      "id": 2,
      "name": "Pipeline Mock 2",
      "mapping_errors": null,
      "mapping": [],
      "output": null,
      "entity_types": [],
      "schema": null,
      "input": null
    },
    {
      "id": 3,
      "name": "Pipeline Mock 3",
      "mapping_errors": null,
      "mapping": [],
      "output": null,
      "entity_types": [],
      "schema": null,
      "input": null
    }
  ]
}
```

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +                  ? `Published on ${moment(new Date(this.props.selectedPipeline.published_on)).format('MMMM DD, YYYY HH:mm')}`
`moment` can handle string dates in different ISO formats  `moment(this.props.selectedPipeline.published_on)`

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/PipelineList.jsx
> +      // TODO: handle errors
:roll_eyes:

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/PipelineList.jsx
> +              defaultMessage={pipeline.published_on ? `Published on ${moment(new Date(pipeline.published_on)).format('MMMM DD')}`
Same `moment` comment.

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/redux.jsx
> +  const COLORS = 10 // This value is the number of colors in the `_color-codes.scss`
This number is something to be revisited in the future...

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/redux.spec.jsx
> +  addPipeline, getPipelines, updatePipeline, INITIAL_PIPELINE, getPipelineById, publishPipeline } from './redux'
_hating loooooooooooooooooooooooooooooooong lines_

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/utils/api.jsx
> +                      resolve({ error, status: res.status })
I know that we talked about this before, but shouldn't this be `reject(new HTTPError(error))`?

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/redux/middleware/client.jsx
> +      if (payload.error) {
wondering why we have a `payload.error` :thinking:

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/utils/constants.jsx
> +export const PROJECT_NAME = 'AUX'
Maybe this one can be an environment variable...

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/css/_section-entityTypes.scss
> +.pipeline-section__entityTypes {
wondering if the name of this file should be `_section-entity-types.scss`

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-producer/conf/docker/setup.sh
> +apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
:joy:

2018-05-31 13:44 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/utils/generateSchemaName.jsx
> +/* This function is used as a typeHook option by `avro.Type.forValue().
Can this method be moved to `index.jsx` or there is a reason to have it alone in one file? Can the file be renamed to `schema-utils.jsx`?

2018-06-01 12:44 UTC, obdulia-losantos commented on aether-ui/conf/check_vars.sh
> +    echo "$2 set!"
:joy:

2018-06-01 13:56 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/utils/index.jsx
> +  return `${s4()}${s4()}-${s4()}-${s4()}-${s4()}-${s4()}${s4()}${s4()}`
:nerd_face:  :upside_down_face: :nerd_face:  :upside_down_face: :nerd_face:  :upside_down_face: :nerd_face:  :upside_down_face:

2018-06-01 13:58 UTC, lordmallam commented on aether-ui/aether/ui/apps.py
> +    verbose_name = 'Aether Kernel UI'
🤷‍♂️

2018-06-01 13:59 UTC, lordmallam commented on aether-producer/conf/docker/setup.sh
> +apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
😕

2018-06-01 14:00 UTC, obdulia-losantos commented on aether-producer/conf/docker/setup.sh
> +apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
![image](https://user-images.githubusercontent.com/8459537/40844702-edd03cce-65b4-11e8-88d4-c79add8e514a.png)

2018-06-01 14:01 UTC, obdulia-losantos commented on aether-producer/conf/docker/setup.sh
> +apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
That old-fashion warning...

2018-06-01 14:02 UTC, obdulia-losantos commented on aether-ui/aether/ui/apps.py
> +    verbose_name = 'Aether Kernel UI'
:woman_shrugging:

2018-06-04 07:45 UTC, quesebifurcan approved these changes

2018-06-04 07:51 UTC, obdulia-losantos approved these changes

2018-06-04 09:29 UTC, merged

2018-06-05 08:59 UTC, admbtlr reviewed
Better late than never!

2018-06-05 08:59 UTC, admbtlr commented on aether-ui/aether/ui/api/tests/__init__.py
> +PIPELINE_EXAMPLE = {
This is kinda nit-picky, but it would be a little clearer if the variable name matched the pipeline name (e.g. `PIPELINE_MOCK_1`)

2018-06-05 08:59 UTC, admbtlr commented on aether-ui/aether/ui/api/tests/test_utils.py
> +                        'revision': '123',
Any particular reason why this is indented like this, as opposed to https://github.com/eHealthAfrica/aether/pull/185/files#diff-f671a712a9f75c140a9918e07841f645R72 ?

2018-06-05 08:59 UTC, admbtlr commented on aether-ui/aether/ui/api/tests/test_views.py
> +        # patching a property will no alter the rest
`# patching a property will noT alter the rest`

2018-06-05 08:59 UTC, admbtlr commented on aether-ui/aether/ui/api/utils.py
> +            [{'description': 'It was not possible to connect to Aether Kernel Server.'}],
Probably better just to say `Aether Kernel`, rather than `Aether Kernel Server`

2018-06-05 08:59 UTC, admbtlr commented on aether-ui/aether/ui/api/utils.py
> +                is_schema_linked = is_object_linked(pipeline.kernel_refs, 'schema', schema_name)
This code block looks like a good candidate for refactoring into a separate function

2018-06-05 08:59 UTC, admbtlr commented on aether-ui/aether/ui/assets/apps/utils/constants.jsx
> +export const MAX_PAGE_SIZE = 1048575
Do we need to change this, based on our recent NPHCDA experiences?

2018-06-05 10:20 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/utils/constants.jsx
> +export const MAX_PAGE_SIZE = 1048575
Not clear on what the NPHCDA experiences were...

2018-06-05 10:25 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/utils/constants.jsx
> +export const MAX_PAGE_SIZE = 1048575
`MAX_PAGE_SIZE` is too big and can head us into many troubles :disappointed: 

This value is in fact a gather legacy in this module, also the comment above :scream:

2018-06-05 10:45 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/utils/constants.jsx
> +export const MAX_PAGE_SIZE = 1048575
Yes. Legacy but used [here](https://github.com/eHealthAfrica/aether/blob/develop/aether-ui/aether/ui/assets/apps/pipeline/redux.jsx#L75) to make sure all records are returned due to lack of proper pagination for now. Will change the comment

2018-06-05 11:15 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/utils/constants.jsx
> +export const MAX_PAGE_SIZE = 1048575
you can use a smaller number...