feat: "identity mapping"
eHealthAfrica/aether pull request #189
Opened 2018-06-04 10:26 UTC by quesebifurcan

This PR adds an "Add Identity Mapping" button, which, when clicked, generates a set of default entity types and mappings.

How to test: 
- Open the ui, paste some json into the "JSON data" section
- Click "Derive Schema"
- Click "Add Identity Mapping"
- Check that the created entity types and mappings were created and that they conform to your schema.

2018-06-04 15:13 UTC, shawnsarwar requested changes
Looking great! A couple of things I noticed:
Auto_0 is automatically used for the entity name. If we could configure that, it would be nice.
The identity mapping should include a id field that's automatically mapped from #!uuid.
The identity schema marks all fields as required which could cause issues. It might be best to have all generated types except id be null optional to keep things flexible since it's not really a proper schema.

2018-06-04 15:15 UTC, obdulia-losantos requested changes
not yet tested locally... but a couple of comments.

2018-06-04 15:15 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/components/Modal.jsx
> +export class Modal extends Component {
:thinking: 

Maybe we should delete the useless last line `export default injectIntl(Modal)` and change this one into `export default class...`

What do you think?

2018-06-04 15:15 UTC, obdulia-losantos commented on aether-ui/package-lock.json
> +{
Is this file really needed?  If not, maybe we can add the rule in `.gitignore` to skip adding everytime someone uses `git add .`

2018-06-04 15:15 UTC, obdulia-losantos commented on aether-ui/package.json
> +    "sinon": "^5.0.10",
As I use to mention, the dependencies uses the `~` flag and not the `^` one that brings to the image the patches and the minor changes. We faced in the past annoying errors when some of the libraries didn't follow the semantic release conventions and include breaking changes as minor releases...

2018-06-04 15:15 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/utils/index.jsx
> +/* Locate a DOM element by its data-qa attribute */
If this is only used in tests maybe you could include it in the test environment package :grimacing:

2018-06-04 15:15 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Input.spec.jsx
> +    const button = component.find('[data-qa="input.identityMapping.btn-apply"]')
couldn't this use your new `findByDataQa` function?

2018-06-04 15:21 UTC, quesebifurcan commented on aether-ui/package-lock.json
> +{
npm recommends using it -- it ensures that we get the exact same set of dependencies (and dependencies of depencies) that we tested the app with.

2018-06-04 15:22 UTC, quesebifurcan commented on aether-ui/package.json
> +    "sinon": "^5.0.10",
Ah, I see. I just kept whatever npm gave me on install. package-lock.json might help, perhaps (see above)? Will change to `~` though :smile:

2018-06-04 15:25 UTC, obdulia-losantos commented on aether-ui/package-lock.json
> +{
Curious, because in the `aet-ui-setup` you can see that the last version of this file (before taking it out) only included one library...

https://github.com/eHealthAfrica/aether/blob/7683c67bc3c084203989007352b4626203866514/aether-ui/package-lock.json

That's why we removed it.

2018-06-04 15:27 UTC, obdulia-losantos commented on aether-ui/package.json
> +    "sinon": "^5.0.10",
And I have the concern about `package-lock.json` usefulness... :wink:

2018-06-04 15:30 UTC, quesebifurcan commented on aether-ui/package-lock.json
> +{
Ah, ok, I guess I was the first one using it, then (switching to the avsc library a couple of weeks back). It'll lead to a more reproducible build, as far as I can tell, but I'm really not the expert here.

2018-06-05 07:32 UTC, obdulia-losantos approved these changes

2018-06-05 09:56 UTC, shawnsarwar approved these changes

2018-06-06 16:19 UTC, merged