Aet ui schema viewer
eHealthAfrica/aether pull request #194
Opened 2018-06-05 12:12 UTC by lordmallam

#### Related JIRA Ticket [AET-264](https://jira.ehealthafrica.org/browse/AET-264)

Bug fix: Avro schema viewer crashes when unions are applied.  Applies to `Entity Type Viewer` as well

2018-06-05 13:42 UTC, obdulia-losantos requested changes
Could you include these cases in the tests?

2018-06-05 14:03 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/redux.jsx
> +    highlightDestination.push(rule.destination.replace('$.', ''))
The destination fields don't have the `$` prefix, do they? :thinking:

2018-06-06 07:44 UTC, obdulia-losantos commented
This is the result of using the AVRO schema generated from an XForm... 

![image](https://user-images.githubusercontent.com/8459537/41023714-76195b18-696d-11e8-91af-a7e583998204.png)

This is the expected tree (I removed some of the unions), the union types can contain really complicated nested types.

![image](https://user-images.githubusercontent.com/8459537/41023856-dc83b498-696d-11e8-84d5-0eecd03e967e.png)

Sorry, I never said this was going to be easy :disappointed_relieved:

2018-06-08 12:17 UTC, obdulia-losantos commented
Is this on purpose? I mean the ~index~, ~value~,...

![image](https://user-images.githubusercontent.com/8459537/41157586-914888b8-6b26-11e8-8a37-c880f202e47b.png)

2018-06-08 12:20 UTC, obdulia-losantos commented
I'm going to suggest to transform the mock files from `jsx` to `json` this will let us use them just copying/pasting them :grimacing:

2018-06-08 12:26 UTC, obdulia-losantos commented
An edge case, union with two different types not only null, but do not try to implement this case ;-)

```json
{
  "name": "PlayingWithCoords",
  "type": "record",
  "fields": [
    {
      "name": "location",
      "type": [
        "null",
        {
          "name": "location_geopoint",
          "type": "record",
          "fields": [
            {
              "name": "coordinates",
              "type": {
                "type": "array",
                "items": "float"
              }
            },
            {
              "name": "altitude",
              "type": [
                "null",
                "float"
              ]
            },
            {
              "name": "accuracy",
              "type": [
                "null",
                "float"
              ]
            },
            {
              "name": "type",
              "type": [
                "null",
                "string"
              ]
            }
          ]
        },
        {
          "name": "location_lat_lng",
          "type": "record",
          "fields": [
            {
              "name": "latitude",
              "type": [
                "null",
                "float"
              ]
            },
            {
              "name": "longitude",
              "type": [
                "null",
                "float"
              ]
            },
            {
              "name": "altitude",
              "type": [
                "null",
                "float"
              ]
            },
            {
              "name": "accuracy",
              "type": [
                "null",
                "float"
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

2018-06-08 12:28 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/tests/mock/schema_entityTypes.mock.jsx
> +        'type': ["int", {"name": "data-type", "type": "string"}]
`standard` should have complained here :scream:

2018-06-08 12:28 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/tests/mock/schema_entityTypes.mock.jsx
> +        'type': ["int", {"name": "data-type", "type": "string"}]
AS I mentioned before, it's better to transform this into JSON and use double quotes :wink:

2018-06-08 13:58 UTC, lordmallam commented
Yes the `line-strike` ~index~, ~value~ is on purpose to indicate array items as they are not directly referenced as other properties. The style will be changed to properly represent array items. Any suggestions on how this can be indicated?

2018-06-08 13:58 UTC, lordmallam commented on aether-ui/aether/ui/assets/tests/mock/schema_entityTypes.mock.jsx
> +        'type': ["int", {"name": "data-type", "type": "string"}]
🤔

2018-06-11 09:14 UTC, obdulia-losantos commented
:flushed: 

SCSS lint warnings

```
./aether/ui/assets/css/_section-input.scss
  63:22  warning  Trailing semicolons required  trailing-semicolon

./aether/ui/assets/css/_section-output.scss
  16:1  warning  Space expected between blocks  empty-line-between-blocks
```

React warnings

```
    Warning: Each child in an array or iterator should have a unique "key" prop.
    
    Check the render method of `AvroSchemaViewer`. See https://fb.me/react-warning-keys for more information.
        in li (created by AvroSchemaViewer)
        in AvroSchemaViewer (created by WrapperComponent)
        in WrapperComponent
```

2018-06-11 10:19 UTC, obdulia-losantos approved these changes

2018-06-11 11:43 UTC, merged