feat: adding caching of expensive jsonpath.parse calls
eHealthAfrica/aether pull request #203
Opened 2018-06-11 11:53 UTC by shawnsarwar

jsonpath_ng creates a new lexer instance each time .parse() is called. This is extremely slow. This pr adds caching of the result of the parse call, as it's always the same for the same input and can be reused for the subsequent .find() calls. We've replaced the jsonpath_ng.parse(jsonpath).find(obj) call with a single call to the static CachedParser of CachedParser.find(jsonpath, obj).

As a secondary note, this exposed an unwanted Django behavior. In debug mode, all db calls are cached causing unbounded memory use expansion. We now detect debug mode and on a random basis, there's a 1% chance the db cache will be cleared when performing entity extraction. This keeps memory stable while running in debug mode.

2018-06-11 12:50 UTC, obdulia-losantos requested changes

2018-06-11 12:50 UTC, obdulia-losantos commented on aether-kernel/aether/kernel/api/utils.py
> +    from django import db
this debug value is already in django settings

```python

from django.conf import settings

if settings.DEBUG:
    # ...
```

2018-06-11 12:50 UTC, obdulia-losantos commented on aether-kernel/aether/kernel/api/utils.py
> +    # memory usage. In debug, we must periodically call db.reset_queries() periodically to avoid
we must **periodically** call db.reset_queries() **periodically** to... :thinking:

2018-06-11 12:50 UTC, obdulia-losantos commented on aether-kernel/aether/kernel/api/utils.py
> +        for datum in matches:
_datum_  / _data_
_forum_ / _fora_
...

back to Latin classes :nerd_face:

2018-06-11 12:56 UTC, quesebifurcan requested changes

2018-06-11 12:56 UTC, quesebifurcan commented on aether-kernel/aether/kernel/api/utils.py
> +
An alternative solution would be to just start the local server with `DEBUG="false"` (set this in `docker-compose.yml`) whenever we need to test code which generates a lot of debug-related artifacts. It would be nice to keep environment-specific details out of the code (if possible).

2018-06-11 12:56 UTC, quesebifurcan commented on aether-kernel/aether/kernel/api/utils.py
> +            CachedParser.cache[path] = deepcopy(jsonpath_ng.parse(path))
Why do we need `deepcopy` here? Is the result of `jsonpath_ng.parse` mutated somewhere?

2018-06-11 12:58 UTC, shawnsarwar commented on aether-kernel/aether/kernel/api/utils.py
> +            CachedParser.cache[path] = deepcopy(jsonpath_ng.parse(path))
Ah, forgot that was still there. I grew deeply paranoid at a number of times trying to track this down.

2018-06-11 12:59 UTC, shawnsarwar commented on aether-kernel/aether/kernel/api/utils.py
> +
I'm open to either; I thought adding the option to have it run in debug would be less problematic than forcing people to run in production mode or have a giant memory leak.

2018-06-11 13:02 UTC, shawnsarwar commented on aether-kernel/aether/kernel/api/utils.py
> +
@obdulia-losantos ; which do you prefer? Check if debug and flush or ignore the leaky behavior in debug?

2018-06-11 13:10 UTC, obdulia-losantos commented
Stupid question, did you take into consideration the Django cache framework? I'm not really sure if this only applies to urls or to any piece of data you want to :thinking: 

https://docs.djangoproject.com/en/2.0/topics/cache/

2018-06-11 13:31 UTC, tooxie commented on aether-kernel/aether/kernel/api/utils.py
> +        for datum in matches:
Oh, latin! I thought it was german.

2018-06-11 13:35 UTC, obdulia-losantos commented on aether-kernel/aether/kernel/api/utils.py
> +
Note: take in mind that the tests are always run with `DEBUG=False`. This is due to the ### behavior of the debug toolbar in tests :unamused:

I agree with @quesebifurcan about keeping the code "agnostic" of this kind of issues. But also see your problem.

Maybe you can use this option locally to activate a cron job that reset the db every X minutes:
https://github.com/eHealthAfrica/aether/blob/develop/aether-common-module/aether/common/conf/settings.py#L252-L259

But maybe this is too much effort for a simple problem. :see_no_evil:

2018-06-11 13:38 UTC, shawnsarwar commented
@obdulia-losantos I took a look at it, but decided not to primarily as I didn't want to tie the functionality to Django since we'll probably want to externalize it into a consumer in the near future.

2018-06-14 13:22 UTC, shawnsarwar commented on aether-kernel/aether/kernel/api/utils.py
> +
I decided to leave the leak in DEBUG=true and the doc on CacheParser talking about the error.

2018-06-14 13:27 UTC, quesebifurcan submitted a review, later dismissed

2018-06-14 13:30 UTC, obdulia-losantos commented on aether-kernel/aether/kernel/api/utils.py
> +import os
is this `os` still in use?

2018-06-14 14:38 UTC, obdulia-losantos approved these changes
:see_no_evil:

2018-06-14 14:48 UTC, merged