feat: (ui) mapping errors indicators
eHealthAfrica/aether pull request #205
Opened 2018-06-12 12:24 UTC by lordmallam

Indicates errors on mapping sections

#### Related JIRA ticket [AET-273](https://jira.ehealthafrica.org/browse/AET-273)

2018-06-12 13:55 UTC, sabeen commented
one small thing: Can we not show the green dot in the output heading, if there are no mappings yet?

2018-06-13 07:11 UTC, tooxie requested changes

2018-06-13 07:11 UTC, tooxie commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +    console.log(nextProps.selectedPipeline)
Could we remove logging statements from production?

2018-06-13 07:11 UTC, tooxie commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Mapping.jsx
> +      ).length > 0
What about [find()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) instead of `filter()`?
```js
const hasError = (source, destination = null) => {
  return Boolean(this.props.selectedPipeline.mapping_errors.find(
    (error) => (error.path && (error.path === source || error.path === destination))
  ));
};
```

2018-06-13 07:11 UTC, tooxie commented on aether-ui/aether/ui/assets/css/_pipeline.scss
> +    height: .8em;
I think we should stick to either `em`s or `rem`s, but not mix them both.

2018-06-13 07:11 UTC, tooxie commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +                  ? 'red' : 'green'}`} /> }
You could reuse `hasError` here.

2018-06-13 07:52 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Mapping.jsx
> +      ).length > 0
Regarding `find` first we need to decide if we want to support IE :see_no_evil: 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

2018-06-13 08:32 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +                  ? 'red' : 'green'}`} /> }
I rather not loop through the entire error list to determine if theres an error.

2018-06-13 08:32 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +    console.log(nextProps.selectedPipeline)
My bad...

2018-06-13 08:34 UTC, tooxie commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Mapping.jsx
> +      ).length > 0
Arrow functions, which we use extensively, are not supported in IE. Are we transpiling the code?

2018-06-13 08:36 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Mapping.jsx
> +      ).length > 0
yes, with babel.

2018-06-13 08:38 UTC, sabeen commented on aether-ui/aether/ui/assets/css/_pipeline.scss
> +    height: .8em;
Sometimes we want to have rem to have some kind of "fixed" unit for margins and paddings to better align items. And in some cases we use em to make it relative to the parents font-size, f.e. in buttons, where you want to adjust the padding according to the size of the button, or within text. It is not always obvious when to use what, but in this case it is related to the heading of the section, and theoretically if you decided to make that heading relative bigger or smaller, that circle indicator would grow or shrink according to the headings font size. Which is the intended behavior.

2018-06-13 08:41 UTC, tooxie commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +                  ? 'red' : 'green'}`} /> }
Why is it ok to loop through the entire error list in `hasError` but not here? Why is here `mapping_errors.length` enough, but in `hasError` we check what the error actually has?

2018-06-13 08:42 UTC, admbtlr commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Mapping.jsx
> +      ).length > 0
It would be nice to support IE if we can, but I don't think it's worth stressing over. Has anyone tested the UI in IE?

Maybe it would be good to add an explanatory comment like `Using filter rather than filter for IE support`

2018-06-13 08:42 UTC, admbtlr commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Mapping.jsx
> +      <div key={rule.id} className={`${hasError(rule.source, rule.destination) && 'error'} rule`}>
There needs to be a moratorium on using $. My first thought was "what's jquery doing here?", then "why is this a Sass variable?", and let's not even mention PHP...

2018-06-13 08:42 UTC, admbtlr commented on aether-ui/aether/ui/assets/css/_pipeline.scss
> +    height: .8em;
They mean different things. `em` is kinda locally scoped, while `rem` is global, and each one makes more sense in certain contexts.

2018-06-13 08:42 UTC, admbtlr commented on aether-ui/aether/ui/assets/css/_pipeline.scss
> +    height: .8em;
OTOH when you're down to like 0.8 of something, it's probably pretty arbitrary... what do you think @sabeen ?

2018-06-13 08:45 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +                  ? 'red' : 'green'}`} /> }
Because `hasError` is for a specific error to display an icon against the problematic mapping. In this case, i only need to know if theres an error or not (holistically)

2018-06-13 08:46 UTC, tooxie commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Mapping.jsx
> +      ).length > 0
Then we can polyfill `Array.prototype.find` as well.

2018-06-13 08:53 UTC, sabeen commented on aether-ui/aether/ui/assets/css/_pipeline.scss
> +    height: .8em;
why, because it is below 0? It is ok, you have to make fine adjustments, and using a relation to the font size is good.

2018-06-13 08:54 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Mapping.jsx
> +      ).length > 0
:+1:

2018-06-13 08:56 UTC, admbtlr commented on aether-ui/aether/ui/assets/css/_pipeline.scss
> +    height: .8em;
Ah, OK, you beat me to it :)

2018-06-13 08:56 UTC, admbtlr commented on aether-ui/aether/ui/assets/css/_pipeline.scss
> +    height: .8em;
Yes, you're right, I take back my comment about it being arbitrary :)

2018-06-13 08:57 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Mapping.jsx
> +      <div key={rule.id} className={`${hasError(rule.source, rule.destination) && 'error'} rule`}>
Hehehehe... that means we shouldn't use template strings?

2018-06-13 09:01 UTC, tooxie commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +                  ? 'red' : 'green'}`} /> }
Alright. You can drop `> 0` from both conditions btw.

2018-06-13 09:05 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +                  ? 'red' : 'green'}`} /> }
If i drop it `0` gets rendered `if this.props.selectedPipeline.mapping.length === 0`

2018-06-15 09:53 UTC, tooxie commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +                  ? 'red' : 'green'}`} /> }
In my opinion that's an effect of misusing a binary operator as a conditional statement (but that's something we discussed already 😄 )

2018-06-15 09:54 UTC, tooxie approved these changes

2018-06-18 12:35 UTC, merged