WIP --do not merge | Feat/elasticsearch consumer
eHealthAfrica/aether pull request #216
Opened 2018-06-18 16:19 UTC by shawnsarwar

I've modified the toy elasticsearch consumer to work with our current setup. The consumer needs some refactor, but it's now based on the consumer-sdk. If you need ES, this should work well for now. Take a look at the sample index in the /index folder for supported syntax. Currently it handles parent child relationships and creation of a location geojson object from existing fields. (It MUST be named location.)

2018-06-18 17:19 UTC, shawnsarwar commented
Before running create an ES index in the /index sub folder for the module. If you create a geolocation in the index, the consumer will attempt to find matching lat and long fields in the data. The names of the types in the index correspond to kafka topics.

Once you're setup, run the docker-compose-es.yml file from the base Aether folder. This expects docker-compose.yml and docker-compose-connect.yml to already be running.

2018-06-30 12:40 UTC, quesebifurcan requested changes
Nice! I tested a couple of entities/indices and it seems to work well. Nice to see more specific exceptions in the code.

Some minor changes suggested below.

2018-06-30 12:40 UTC, quesebifurcan commented on consumer-elasticsearch/aether_elasticsearch/elasticsearch_consumer.py
> +                ["localhost", "elasticsearch"], sniff_on_start=False)
Would it make sense to be able to set these values from a config file/environment variables? Thinking of Kubernetes, where this consumer might run in a different pod than the es instance itself (and would be referred to by its hostname).

2018-06-30 12:40 UTC, quesebifurcan commented on consumer-elasticsearch/aether_elasticsearch/elasticsearch_consumer.py
> +            print("Could not connect to Elasticsearch Instance")
Many print statements in this file could be turned into logging statements. Stdout wouldn't be so cluttered and devops can filter messages by severity.

2018-06-30 12:40 UTC, quesebifurcan commented on consumer-elasticsearch/aether_elasticsearch/elasticsearch_consumer.py
> +            data = json.load(f)
When testing different indices, I got a lot of errors from here. The reason was always a json error in my hand-edited file, but it wasn't so obvious that that was actually the error. Something about "Malformed config file" would be great to have.

2018-06-30 12:40 UTC, quesebifurcan commented on consumer-elasticsearch/aether_elasticsearch/elasticsearch_consumer.py
> +            pass
`pass` is probably a leftover from a previous version?

2018-06-30 12:40 UTC, quesebifurcan commented on consumer-elasticsearch/aether_elasticsearch/elasticsearch_consumer.py
> +                        pass
It looks like this try/except block could be replaced by `val.get(name, None)` or `val.get(name)`?

2018-07-17 18:42 UTC, shawnsarwar commented
This has been moved out of aether into aether-elastic-consumer

2018-07-17 18:42 UTC, closed without merging