Add timeout parameter to client
eHealthAfrica/aether pull request #221
Opened 2018-06-21 16:21 UTC by tooxie

It's important that no calls to any service leave the system
unresponsive, consuming resources for a long period. Timeouts by default
are counted in minutes, which is ridiculous for any web app.

If any call took longer a few seconds then it must be looked into, with
long timeouts we won't even know that there is a problem.

**Note:** This PR adds no tests. I tried but since these are not unit but integration tests, I couldn't get them to run locally in a short period of time, so I will wait for someone to help me set it up.

2018-06-25 08:11 UTC, quesebifurcan requested changes

2018-06-25 08:11 UTC, quesebifurcan commented on aether-utils/aether-client/aether/client.py
> +        req = requests.get(url, auth=self.auth, timeout=getattr(self, 'timeout'))
Just a small detail -- why `getattr(self, 'timeout')` instead of `self.timeout`?

2018-06-25 08:11 UTC, quesebifurcan commented on aether-utils/aether-client/aether/client.py
> +    def __init__(self, url=None, username=None, password=None, timeout=3):
Good catch! How about including timeouts for `requests.post` as well?

2018-06-26 08:07 UTC, tooxie commented on aether-utils/aether-client/aether/client.py
> +        req = requests.get(url, auth=self.auth, timeout=getattr(self, 'timeout'))
Because this class is mostly used as base class for other to extend from, which means that `__init__()` can be overwritten and `self.timeout` never defined. With `getattr` we get `None` instead of an `AttributeError` exception.

2018-06-26 08:24 UTC, quesebifurcan approved these changes

2018-06-26 08:26 UTC, merged