fix: (ui) check for recursive schemas
eHealthAfrica/aether pull request #236
Opened 2018-06-29 11:03 UTC by lordmallam

Temporary mitigation when recursive schemas are used.

- Prevents `Input` component from crashing
- Displays `You have provided a recursive schema. Currently not supported` message 

Related JIRA ticket: [AET-290](https://jira.ehealthafrica.org/browse/AET-290)

Recursive schema = `{
  "name": "recursive",
  "type": "record",
  "fields": [
    {
      "name": "recursive",
      "type": "recursive"
    }
  ]
}`

2018-06-29 11:25 UTC, shawnsarwar submitted a review, later dismissed

2018-06-29 11:28 UTC, obdulia-losantos requested changes
The way of indicating the "translatable" message is not correct

2018-06-29 11:30 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Input.jsx
> +            errorHead: 'You have provided a recursive schema. Currently not supported'
this must use the `formatMessage(MESSAGES.recursiveError)` option.

Take a look at https://github.com/eHealthAfrica/aether/blob/1ac4f475e5625389c9527f08e6902f5f2db8b3e5/aether-ui/aether/ui/assets/apps/components/NavBar.jsx

2018-06-29 11:51 UTC, lordmallam commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Input.jsx
> +            errorHead: 'You have provided a recursive schema. Currently not supported'
This is setting the state value, formatting happens [here](https://github.com/eHealthAfrica/aether/pull/236/files/4ab7f7a290f317d7549329717836da0cd87dc9a9#diff-9e33e8d32267278e6482688e5c123949R155)

2018-06-29 12:02 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Input.jsx
> +            errorHead: 'You have provided a recursive schema. Currently not supported'
But it's wrong! You are assigning the same id to two different messages, and react-int is going to complain! or it should.

There are many ways of doing this, you can create the MESSAGE dictionary and set the header using the message id and call it in the render process... many, many ways.

```javascript
this.setState({
  error: ...,
  errorHead: MESSAGE.mySpecificError
})

// later in the render step
```javascript 
const {formatMessage} = this props.intl

// ...
 <h4 className='hint-title'>
  { formatMessage(this.state.errorHead) }
</h4>
{this.state.error}

2018-06-29 12:27 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Input.jsx
> +        defaultMessage: this.state.errorHead,
this is the text not the state :wink:

2018-06-29 13:05 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Input.jsx
> +    const MESSAGES = defineMessages({
This can be declared outside the class. But I'm not going to complain if you keep it here ;-)

2018-06-29 13:05 UTC, obdulia-losantos submitted a review, later dismissed

2018-06-29 13:25 UTC, obdulia-losantos approved these changes
:joy:

2018-06-29 17:38 UTC, merged

2018-06-30 10:23 UTC, quesebifurcan commented
The difference between Firefox and Chrome (didn't test with other browsers yet) is that Firefox bails out earlier, throwing `InternalError` with the message "too much recursion". This is not caught by the change in this PR.

Chrome happily continues a bit longer and throws a `RangeError`. This PR addresses that.

Could we try to make the recursion detection work for Firefox as well?

2018-06-30 10:43 UTC, obdulia-losantos commented
Good catch!

2018-06-30 10:44 UTC, obdulia-losantos commented
What happens with IE, Edge, Safari and... :see_no_evil: