chore: unify ports with start and start_dev commands
eHealthAfrica/aether pull request #277
Opened 2018-07-11 15:12 UTC by obdulia-losantos

This will simplify the `aether-bootstrap` setup (all the custom `uwsgi.ini` files could be removed)

- Dynamic ports with `start` command using `WEB_SERVER_PORT` env var.
- ODK Module port is `8001` (`9001` in tests) to use ODK Collect run it behind nginx.
- CouchDB-Sync port is `8006` (`9006` in tests).
- Unify indentation to 4 spaces in scripts.
- Updated README

2018-07-12 15:01 UTC, tooxie submitted a review, later dismissed

2018-07-12 15:01 UTC, tooxie commented on aether-couchdb-sync-module/entrypoint.sh
> +        ./manage.py collectstatic --noinput --noinput --clear --verbosity 0
I would set the verbosity level based on the `$DEBUG` env var.

2018-07-12 15:01 UTC, tooxie commented on aether-couchdb-sync-module/entrypoint.sh
> +        /usr/local/bin/uwsgi --ini /code/conf/uwsgi.ini --http 0.0.0.0:$WEB_SERVER_PORT $LOGGING
What about:
```sh
/usr/local/bin/uwsgi \
    --ini /code/conf/uwsgi.ini \
    --http 0.0.0.0:$WEB_SERVER_PORT \
    $DISABLE_LOGGING
```
Just a nitpick, up to you.

2018-07-12 15:01 UTC, obdulia-losantos commented on aether-couchdb-sync-module/entrypoint.sh
> +        /usr/local/bin/uwsgi --ini /code/conf/uwsgi.ini --http 0.0.0.0:$WEB_SERVER_PORT $LOGGING
:+1:

2018-07-16 08:48 UTC, quesebifurcan requested changes

2018-07-16 08:48 UTC, quesebifurcan commented on aether-couchdb-sync-module/entrypoint.sh
> +        cp ./VERSION /var/www/static/VERSION 2>/dev/null || :
Would it be possible to always include the version here (and exit with error if it's not present)? Just so it's not accidentally left out when building an image. Are there any situations in which we don't want to pass in a version?

2018-07-16 09:05 UTC, obdulia-losantos commented on aether-couchdb-sync-module/entrypoint.sh
> +        cp ./VERSION /var/www/static/VERSION 2>/dev/null || :
:thinking:

2018-07-16 09:12 UTC, admbtlr commented on aether-couchdb-sync-module/entrypoint.sh
> +        cp ./VERSION /var/www/static/VERSION 2>/dev/null || :
We want to ditch the version file and rely on `VERSION` and `REVISION`/`COMMIT` env vars being set on all the images at build time.

But this should probably happen in a separate PR that also changes `release.sh`, so maybe it's best to leave this as is for now?

2018-07-16 10:44 UTC, quesebifurcan approved these changes

2018-07-16 10:44 UTC, quesebifurcan commented on aether-couchdb-sync-module/entrypoint.sh
> +        cp ./VERSION /var/www/static/VERSION 2>/dev/null || :
Alright, that makes sense. See https://jira.ehealthafrica.org/browse/AET-317 for details.

2018-07-16 11:49 UTC, merged