Add helm package for UI
eHealthAfrica/aether pull request #284
Opened 2018-07-12 22:32 UTC by tooxie

2018-07-13 09:33 UTC, obdulia-losantos commented on aether-ui/entrypoint.sh
> -  export PGPASSWORD=$RDS_PASSWORD
Why are your removing these lines? They are necessary to connect to postgres :thinking:

2018-07-13 09:37 UTC, tooxie commented on aether-ui/entrypoint.sh
> -  export PGPASSWORD=$RDS_PASSWORD
Because the deployment generates the correct environment variables, there is no need to rename them now. See:

https://github.com/eHealthAfrica/aether/blob/aa23af18eea4d7d549ba6ac2e3d76123ed9f0bd0/helm/ui/templates/deployment.yaml#L96-L108

2018-07-13 09:40 UTC, obdulia-losantos commented on aether-ui/entrypoint.sh
> -  export PGPASSWORD=$RDS_PASSWORD
What happens locally? This is also used without helm :flushed:

2018-07-13 09:48 UTC, tooxie commented on aether-ui/entrypoint.sh
> -  export PGPASSWORD=$RDS_PASSWORD
I checked the `aether-ui` source code and I couldn't find any mentions to these variables, but I see that `docker-compose-base.yml` sets them too. I'll issue a fix in a new PR. Is there any other place that you know these names should be updated?

2018-07-13 09:50 UTC, obdulia-losantos commented on aether-ui/entrypoint.sh
> -  export PGPASSWORD=$RDS_PASSWORD
it's not used by django it's used by the psql commands `pg_isready`, `psql`, `createdb`...

2018-07-13 09:53 UTC, obdulia-losantos commented on aether-ui/entrypoint.sh
> -  export PGPASSWORD=$RDS_PASSWORD
https://www.postgresql.org/docs/9.6/static/libpq-envars.html

2018-07-13 09:55 UTC, tooxie commented on aether-ui/entrypoint.sh
> -  export PGPASSWORD=$RDS_PASSWORD
Yes, and they are being set with the correct name from the start. `RDS_PASSWORD` doesn't exist any more, it's now called `PGPASSWORD`, so there is no need to rename it.

2018-07-13 10:18 UTC, tooxie commented on aether-ui/entrypoint.sh
> -  export PGPASSWORD=$RDS_PASSWORD
https://github.com/eHealthAfrica/aether/pull/285

2018-07-13 11:27 UTC, MrPink requested changes

2018-07-13 11:27 UTC, MrPink commented on helm/ui/Chart.yaml
> +description: A Helm chart for Kubernetes
Can we make this more descriptive, this is used when you search Helm packages on a repository

2018-07-13 11:27 UTC, MrPink commented on helm/ui/templates/deployment.yaml
> +          livenessProbe:
I wonder if it makes sense to add an HTTP header to make clear what is hitting the `/health` endpoint, see https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ under `httpHeaders`

2018-07-13 11:27 UTC, MrPink commented on helm/ui/templates/deployment.yaml
> +          readinessProbe:
same here

2018-07-13 11:27 UTC, MrPink commented on helm/ui/templates/ingress.yaml
> +    alb.ingress.kubernetes.io/scheme: "internet-facing"
did we want AWS specific things in the ingress

2018-07-13 11:27 UTC, MrPink commented on helm/ui/values.yaml
> +    alb.ingress.kubernetes.io/security-groups: "alb-ingress-controller.dev.k8s.eha.im"
probably makes sense to consolidate the annotations for `alb` in one file

2018-07-13 11:27 UTC, MrPink commented on helm/ui/values.yaml
> +  rdsDbHost: dev-k8s-eha-im.cpqsfknb8sgc.eu-west-1.rds.amazonaws.com
We can think about  `ExternalName service` for this perhaps - https://kubernetes.io/docs/concepts/services-networking/service/ but this doesn't have to be immediate.

2018-07-13 11:28 UTC, MrPink commented
@tooxie can you also write how this should be tested in terms of installation

2018-07-13 14:12 UTC, tooxie commented on helm/ui/templates/deployment.yaml
> +          livenessProbe:
That information does not get logged, where does it show up? How would we use it?

2018-07-13 14:13 UTC, tooxie commented on helm/ui/templates/ingress.yaml
> +    alb.ingress.kubernetes.io/scheme: "internet-facing"
I didn't know that was AWS-specific. Will move it back to the values file.

2018-07-13 14:15 UTC, tooxie commented on helm/ui/values.yaml
> +  rdsDbHost: dev-k8s-eha-im.cpqsfknb8sgc.eu-west-1.rds.amazonaws.com
I like the idea. But yeah, I also agree that we better think that through and introduce it for all charts at once.

2018-07-13 14:32 UTC, tooxie commented
@MrPink what do you mean by "tested in terms of installation"? Installation instructions? Automated tests? Manual tests? All of the above?

2018-07-17 08:33 UTC, MrPink commented on helm/ui/templates/deployment.yaml
> +          livenessProbe:
does it not get logged on debug?

2018-07-17 08:34 UTC, MrPink commented
as in the `helm install` + `override`

2018-07-17 08:43 UTC, tooxie commented on helm/ui/templates/deployment.yaml
> +          livenessProbe:
I'll double check, but I don't remember it being logged.

2018-07-17 09:13 UTC, tooxie commented
@MrPink there is no special instalation instructions for this package.

2018-07-17 09:35 UTC, obdulia-losantos commented on helm/ui/templates/nginx-config-map.yaml
> +      # Protected media
There is no media content in `ui`, you can remove this if you want.

2018-07-17 09:37 UTC, obdulia-losantos commented on helm/ui/templates/init-config-map.yaml
> +    chmod -R 775 /media
Nice to have but not needed. :wink:

2018-07-17 09:45 UTC, obdulia-losantos requested changes
`WEB_SERVER_PORT`is now required to start the container, even with the `start` command.

2018-07-17 09:45 UTC, obdulia-losantos commented on helm/ui/templates/deployment.yaml
> +          defaultMode: 0744
I missed this block

```
        # `WEB_SERVER_PORT` is kept around for compatibility with the old tests,
        # which are using different ports in different environments. Once all
        # tests have been updated to run inside the cluster, `WEB_SERVER_PORT`
        # can be removed.
        - name: WEB_SERVER_PORT
          value: {{ quote .Values.webserverPort }}
```

2018-07-17 11:54 UTC, tooxie commented on helm/ui/templates/deployment.yaml
> +          defaultMode: 0744
Added.

2018-07-17 11:56 UTC, obdulia-losantos approved these changes

2018-07-17 16:56 UTC, tooxie commented on helm/ui/templates/deployment.yaml
> +          livenessProbe:
Checked, they don't show up anywhere.

2018-07-18 08:17 UTC, MrPink approved these changes

2018-07-18 08:42 UTC, merged