fix: create readonly user for non-core aether modules
eHealthAfrica/aether pull request #293
Opened 2018-07-16 22:49 UTC by quesebifurcan

Create readonly user in kernel database. This role can be used
by non-core Aether modules such as `aether-producer`.

The user is granted read permissions for the following tables:
- kernel_entity
- kernel_mapping
- kernel_projectschema
- kernel_schema

NOTE:
The main script is in python, not pure SQL. I tried the latter, but
there were simply too many variables to interpolate; quoting gets 
tricky when the same variable has to serve as both identifier and 
literal.

Partly resolves https://jira.ehealthafrica.org/browse/AET-315

2018-07-17 14:51 UTC, tooxie requested changes
Yayyy for the principle of least privilege!! \o/ 😄 🎉

2018-07-17 14:51 UTC, tooxie commented on helm/kernel/templates/deployment.yaml
> +              key: kernel-readonly-db-username
I know this is consistent with the current state of the chart, but in #280 we are moving all non-password values from the secret to the values file.

2018-07-17 14:53 UTC, quesebifurcan commented on helm/kernel/templates/deployment.yaml
> +              key: kernel-readonly-db-username
ah, that makes sense. Never seemed like a secret to me, this one.

2018-07-17 18:39 UTC, shawnsarwar submitted a review, later dismissed

2018-07-17 21:23 UTC, tooxie approved these changes

2018-07-17 21:24 UTC, tooxie requested changes

2018-07-17 21:24 UTC, tooxie commented on aether-kernel/sql/create_readonly_user.py
> +        'port': 5432,
Please get this from the environment as well.

2018-07-18 08:29 UTC, obdulia-losantos commented on aether-kernel/sql/create_readonly_user.py
> +GRANT CONNECT ON DATABASE {database} TO {role};
Could you include this instruction before the GRANT ones? Just to remove previous privileges added manually.

```SQL
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM {role};
```

2018-07-18 08:31 UTC, obdulia-losantos commented on aether-kernel/sql/create_readonly_user.py
> +GRANT CONNECT ON DATABASE {database} TO {role};
Better 

```sql
REVOKE  ALL PRIVILEGES ON DATABASE {database} FROM {role} CASCADE;
```

https://www.postgresql.org/docs/9.6/static/sql-revoke.html

2018-07-18 08:49 UTC, obdulia-losantos commented on aether-kernel/sql/create_readonly_user.py
> +REVOKE ALL PRIVILEGES ON DATABASE {database} FROM {role} CASCADE;
:+1:

2018-07-18 08:49 UTC, obdulia-losantos approved these changes

2018-07-18 12:23 UTC, tooxie approved these changes

2018-07-18 14:53 UTC, merged