chore: fix setup and start scripts
eHealthAfrica/aether pull request #343
Opened 2018-09-04 11:02 UTC by obdulia-losantos

2018-09-05 09:10 UTC, admbtlr requested changes

2018-09-05 09:10 UTC, adamvert commented on README.md
> +  `--killl` | `-k`  will kill running containers
typo?

2018-09-05 09:10 UTC, adamvert commented on scripts/docker_start.sh
> +#   --killl | -k  will kill running containers
typo

2018-09-05 09:10 UTC, adamvert commented on README.md
> +  `--killl` | `-k`  will kill running containers
and what's the difference between `-f` and `-k`?

2018-09-05 09:10 UTC, adamvert commented on README.md
> +    Another value will start all containers.
Actually "Any other...." is slightly more natural here than "Another..."

2018-09-05 09:17 UTC, adamvert commented
Reading the README, I'm a bit confused: should I be using `./scripts/docker_start.sh` rather than `docker-compose up`? Both are mentioned, and it's not immediately clear to me why...

2018-09-05 09:24 UTC, obdulia-losantos commented
`docker_start.sh` takes care of the order in which the containers must be started to work smoothly and without health errors, missing resources...

`docker-compose` starts the containers in the same order they appear in the `docker-compose.yml` file.

We already know that this is not enough :sob:

2018-09-05 12:12 UTC, adamvert commented
I guess this is nothing to do with this PR, but when I run it I get 

```couchdb-sync-rq_1  | psycopg2.OperationalError: FATAL:  database "couchdb-sync" does not exist```

2018-09-05 12:13 UTC, adamvert commented
Also 
![image](https://user-images.githubusercontent.com/1815204/45092474-d6bde980-b115-11e8-9934-5437d299f99f.png)

2018-09-05 12:20 UTC, obdulia-losantos commented
As expected if you are not running gather :sweat_smile:

2018-09-05 12:20 UTC, obdulia-losantos commented
I'll check the `couchdb-sync-rq` error :see_no_evil:

2018-09-05 13:36 UTC, adamvert commented
Ah, true, good point

2018-09-05 13:54 UTC, obdulia-losantos commented
Hopefully this time works :crossed_fingers:

2018-09-07 10:31 UTC, adamvert commented
And now nginx never starts up 💢

2018-09-10 07:53 UTC, admbtlr approved these changes
Everything works fine on a more powerful machine 🎉

2018-09-10 07:53 UTC, obdulia-losantos commented
:tada:

2018-09-10 08:20 UTC, merged