feat(kernel): add attachments to submissions
eHealthAfrica/aether pull request #46
Opened 2018-01-15 10:43 UTC by obdulia-losantos

Finishes https://jira.ehealthafrica.org/browse/AET-88

2018-01-15 10:44 UTC, obdulia-losantos commented on aether-kernel/aether/kernel/api/models.py
> +    project = models.ForeignKey(to=Project, on_delete=models.CASCADE)
I included the option `on_delete` because it's needed to migrate to Django 2
The `related_name` was moved to `Meta` defaults.

2018-01-15 10:46 UTC, obdulia-losantos commented on aether-kernel/aether/kernel/api/models.py
> +        ordering = ['name', 'revision']
Not sure if you need the ordering or not but the pagination class loves to have it :wink:

2018-01-15 10:48 UTC, obdulia-losantos commented on aether-kernel/aether/kernel/api/models.py
> +    return '{submission}/{revision}/{attachment}'.format(
I wanted to include the `mapping_id` in the folder tree but because it is not mandatory within a submission... it could create a lot of problems :disappointed:

2018-01-15 10:51 UTC, obdulia-losantos commented on aether-kernel/aether/kernel/api/serializers.py
> +class ProjectSerializer(DynamicFieldsMixin, serializers.ModelSerializer):
The `DynamicFieldsMixin` enables the option of fetching only a certain set of fields not all of them. I think that this is useful and it's already in use in Gather but if you prefer I can remove it from here...

2018-01-15 14:14 UTC, quesebifurcan commented on aether-kernel/aether/kernel/api/models.py
> +    return '{submission}/{revision}/{attachment}'.format(
Yes, we should fix this. Created https://jira.ehealthafrica.org/browse/AET-111

2018-01-15 14:17 UTC, quesebifurcan commented on aether-kernel/aether/kernel/api/serializers.py
> +class ProjectSerializer(DynamicFieldsMixin, serializers.ModelSerializer):
It's definitely ok to keep it if you think it's useful 👍

2018-01-15 14:19 UTC, admbtlr requested changes

2018-01-15 14:19 UTC, admbtlr commented on aether-kernel/aether/kernel/api/models.py
> +        ordering = ['name', 'revision']
Guess it can't hurt...

2018-01-15 14:19 UTC, admbtlr commented on aether-kernel/aether/kernel/api/migrations/0003_auto_20180112_0938.py
> +                ('sub_revision', models.TextField()),
Can we make this `submission_revision`? `sub_revision` sounds like it might mean something else.

2018-01-15 14:19 UTC, admbtlr commented on aether-kernel/aether/kernel/api/models.py
>      map_revision = models.TextField(default='1')
Ah, I see, there's prior art. I would actually prefer `mapping_revision` here, since `map_revision` also sounds like it could mean something else, but I guess it's too late now...

2018-01-15 14:19 UTC, admbtlr commented on aether-kernel/aether/kernel/api/models.py
> +    return '{submission}/{revision}/{attachment}'.format(
Although it is a bit weird that it's not mandatory. What do you think @shawnsarwar @quesebifurcan ? Should it be possible to have a `submission` without a `mapping_id`?

2018-01-15 14:37 UTC, quesebifurcan approved these changes
Great, well done!

2018-01-15 14:37 UTC, quesebifurcan commented on aether-common/aether/common/kernel/utils.py
> +        return '{kernel_url}/{type}/{id}/'.format(
👍

2018-01-15 15:10 UTC, obdulia-losantos commented on aether-kernel/aether/kernel/api/migrations/0003_auto_20180112_0938.py
> +                ('sub_revision', models.TextField()),
:+1:

2018-01-15 15:13 UTC, obdulia-losantos commented on aether-kernel/aether/kernel/api/models.py
>      map_revision = models.TextField(default='1')
Never it's too late, but this change should be done in another PR...

2018-01-15 16:11 UTC, obdulia-losantos commented on aether-kernel/aether/kernel/api/models.py
> +'''
@quesebifurcan I included a simple data model schema to understand what's going on here...

2018-01-15 16:20 UTC, quesebifurcan commented on aether-kernel/aether/kernel/api/models.py
> +'''
Very nice!

2018-01-16 13:45 UTC, admbtlr approved these changes

2018-01-16 13:59 UTC, merged