chore: refactor docker-compose files/options
eHealthAfrica/aether pull request #48
Opened 2018-01-15 14:55 UTC by obdulia-losantos

Finishes: https://jira.ehealthafrica.org/browse/AET-100

Extracted common settings to `docker-compose-base.yml`. The rest of files extend and override the services declared there.

2018-01-16 13:54 UTC, admbtlr requested changes
I guess you're pretty sick of renaming things by now, so I can do this if you want... :)

2018-01-16 13:54 UTC, admbtlr commented on docker-compose-base.yml
> +#  * ODK Collect Adapter
Let's refer to it as the `ODK Module` everywhere

2018-01-16 13:54 UTC, admbtlr commented on docker-compose-base.yml
> +#  * Mobile CouchDB Sync
Likewise, `CouchDB Sync Module` (it's not necessarily just for mobile)

2018-01-16 13:54 UTC, admbtlr commented on docker-compose-base.yml
> +        build: aether-odk-importer
No `importer` ever! It should be `aether-odk-module`

2018-01-16 13:54 UTC, admbtlr commented on docker-compose-base.yml
> +        build: aether-couchdb-sync
`aether-couchdb-sync-module`

2018-01-16 14:03 UTC, obdulia-losantos commented on docker-compose-base.yml
> +        build: aether-odk-importer
Do you mean `odk-base` to `aether-odk-module`?

2018-01-16 14:05 UTC, admbtlr commented on docker-compose-base.yml
> +        build: aether-odk-importer
I actually meant the `build` and `image` values

2018-01-16 14:05 UTC, admbtlr commented on docker-compose-base.yml
> +            - ./aether-odk-importer:/code
And here too...

2018-01-16 14:08 UTC, obdulia-losantos commented on docker-compose-base.yml
> +        build: aether-odk-importer
`build` is the folder name... are you sure? No problem on that but need confirmation :writing_hand:

2018-01-17 09:27 UTC, admbtlr requested changes
You must hate me by now :)

I think I've left a comment on every name change, so hopefully you can just go through them pretty quickly.

2018-01-17 09:27 UTC, admbtlr commented on README.md
> +#### Aether ODK
**Aether ODK Module**

2018-01-17 09:27 UTC, admbtlr commented on README.md
> +#### Aether CouchDB Sync
**Aether CouchDB Sync Module**

2018-01-17 09:27 UTC, admbtlr commented on docker-compose-base.yml
> +#  * Aether Kernel Module
`Aether Kernel` 

The kernel isn't a module - we have 1 kernel and n modules. Of the 3 modules that we currently have (ODK, CouchDB Sync and Gather), 2 are "core modules" (ODK and CouchDB Sync), while one is a "project module" (Gather).

2018-01-17 09:27 UTC, admbtlr commented on docker-compose-base.yml
> +  # Aether Kernel module
`Aether Kernel`

2018-01-17 09:27 UTC, admbtlr commented on docker-compose-base.yml
> +    build: aether-kernel-module
`aether-kernel`

2018-01-17 09:27 UTC, admbtlr commented on docker-compose-base.yml
> +    image: aether-kernel-module
`aether-kernel`

2018-01-17 09:27 UTC, admbtlr commented on docker-compose-base.yml
> +      - ./aether-kernel-module:/code
`./aether-kernel:/code`

2018-01-17 09:27 UTC, admbtlr commented on docker-compose-kernel.yml
> +#  * Aether Kernel Module
`Aether Kernel`

2018-01-17 09:27 UTC, admbtlr commented on docker-compose-odk.yml
> +#  * Aether Kernel Module
`Aether Kernel`

2018-01-17 09:27 UTC, admbtlr commented on docker-compose-odk.yml
> +  # Aether Kernel module
`Aether Kernel`

2018-01-17 09:27 UTC, admbtlr commented on docker-compose-sync.yml
> +#  * Aether Kernel Module
`Aether Kernel`

2018-01-17 09:27 UTC, admbtlr commented on docker-compose-sync.yml
> +  # Aether Kernel module
`Aether Kernel`

2018-01-17 09:27 UTC, admbtlr commented on docker-compose-sync.yml
> +  # Mobile Sync module
`CouchDB Sync Module`

2018-01-17 09:27 UTC, admbtlr commented on docker-compose-test.yml
> +#  * Aether Kernel Module
`Aether Kernel`

2018-01-17 09:27 UTC, admbtlr commented on docker-compose.yml
> +#  * Aether Kernel Module
`Aether Kernel`

2018-01-17 09:27 UTC, admbtlr commented on docker-compose.yml
> +#  * ODK Collect Module
`ODK Module`

2018-01-17 09:27 UTC, admbtlr commented on docker-compose.yml
> +  # Aether Kernel module
`Aether Kernel`

2018-01-17 09:29 UTC, admbtlr commented
And to justify being a pain: developers who use Aether will be looking at and using these files; we need to get this small stuff exactly right so that we can have everyone who uses Aether speaking the same, unambiguous language.

2018-01-17 09:31 UTC, quesebifurcan reviewed
Looks good, great work! Unrelated to the quality of this PR, but I personally think having 7 different compose files with almost 700 lines of docker-compose configuration is a bit too much for a project this size. I also admit to not understanding exactly why we need the extra compose files. Would be great if @MrPink could take a closer look if he has time -- maybe there's a simpler way to set this up?

2018-01-17 10:11 UTC, obdulia-losantos commented
@adamvert I hope this time is fine or close to! :sweat_smile:

2018-01-17 10:24 UTC, admbtlr approved these changes
🎉 💯

2018-01-17 10:30 UTC, obdulia-losantos commented
:rocket: :roller_coaster:

2018-01-17 10:31 UTC, obdulia-losantos commented
@MrPink whenever you have time! :grimacing: :pray:

2018-01-18 09:43 UTC, MrPink approved these changes

2018-01-18 09:46 UTC, obdulia-losantos commented
@quesebifurcan talking to Will we decide to merge this and in another branch clean up the docker-compose files to make it simpler and clean. :see_no_evil:

2018-01-18 09:47 UTC, merged