wip: add multitenancy model and filter data
eHealthAfrica/aether pull request #483
Opened 2019-02-04 16:56 UTC by obdulia-losantos

- [x] Model `MtInstance` to handle relations between projects and realms
- [x] Added methods to `Project` model (no new fields) (yes, also cleaning a little bit)
- [x] Create a new Project using the REST API assigns it to the current "realm" (contained in the "aether-realm" cookie)
- [x] Propagate projects also assigns the realm.
- [x] In the serializer forms, the "combos" data is restricted by current realm.
- [ ] Tests, tests, tests
- [ ] Include same changes in `odk`, `couchdb-sync` and `ui` (and there are no projects here :unamused: )

2019-03-15 11:06 UTC, admbtlr requested changes
I'm about half way through, here are my comments so far...

Generally speaking, this is AMAZING! 😍 😍 😍 😍 
I think it's one of the best thought out and implemented PRs I've ever reviewed. 👏 👏 👏

2019-03-15 11:06 UTC, admbtlr commented on README.md
> +- `DEFAULT_REALM`, `aether` The default realm for the objects created
```suggestion
- `DEFAULT_REALM`, `aether` The default realm for artefacts created
```

2019-03-15 11:06 UTC, admbtlr commented on README.md
> +  while multi-tenancy was not enabled.
```suggestion
  if multi-tenancy is not enabled.
```

2019-03-15 11:06 UTC, admbtlr commented on README.md
> +  - The surveyors could be assigned to more than one realm.
Is this still the case?

2019-03-15 11:06 UTC, admbtlr commented on README.md
> +    an instance assigned to one realm but not to many realms without sharing
```suggestion
    an instance assigned to a single realm but not to multiple realms without sharing
```

2019-03-15 11:06 UTC, admbtlr commented on aether-common-library/aether/common/multitenancy/README.md
> +> A place for everything and everything in its place.
🤣

2019-03-15 11:06 UTC, admbtlr commented on aether-common-library/aether/common/multitenancy/README.md
> +relation, i.e. `MULTITENANCY_MODEL='my_app.MyModel'`.
```suggestion
relation, e.g. `MULTITENANCY_MODEL='my_app.MyModel'`.
```

2019-03-15 11:06 UTC, admbtlr commented on aether-common-library/aether/common/multitenancy/README.md
> +  or if it is not accessible by current realm, otherwise returns the object.
I'm a little confused here: so if there's an object that is not accessible by the current realm, it could return `404 NOT FOUND` _or_ `403 FORBIDDEN`?

2019-03-15 11:06 UTC, admbtlr commented on aether-common-library/aether/common/multitenancy/README.md
> +  or if it is not accessible by current realm, otherwise returns the object.
Ah, OK, I get it - you can use either depending on the context.

2019-03-15 11:06 UTC, admbtlr commented on aether-common-library/aether/common/multitenancy/views.py
> +        Custom method that raises NO_FOUND error
```suggestion
        Custom method that raises NOT_FOUND error
```

2019-03-15 11:06 UTC, admbtlr commented on aether-common-library/aether/common/multitenancy/README.md
> +- `get_object_or_404(pk)` raises `NO_FOUND` error if the object does not exist
```suggestion
- `get_object_or_404(pk)` raises `NOT_FOUND` error if the object does not exist
```

2019-03-15 11:06 UTC, admbtlr commented on aether-common-library/aether/common/multitenancy/views.py
> +        - ``get_object_or_404(pk)`` raises NO_FOUND error if the instance
```suggestion
        - ``get_object_or_404(pk)`` raises NOT_FOUND error if the instance
```

2019-03-15 11:13 UTC, obdulia-losantos commented on README.md
> +  - The surveyors could be assigned to more than one realm.
Yes, but only in the admin section, using the REST API is hard to do because the user is not accessible.

2019-03-15 12:33 UTC, adamvert commented on aether-kernel/aether/kernel/api/tests/test_multitenancy.py
> +        # no affected by realm value
```suggestion
        # not affected by realm value
```

2019-03-18 13:07 UTC, admbtlr approved these changes
💥

2019-03-18 14:12 UTC, merged