feat: UI multi contracts per pipeline
eHealthAfrica/aether pull request #487
Opened 2019-02-13 08:58 UTC by lordmallam

This implements the Mockup designs referenced in  [AET-348](https://jira.ehealthafrica.org/browse/AET-348) , [AET-349](https://jira.ehealthafrica.org/browse/AET-349)
Allowing a user to create multiple contracts displayed as tabs within a  pipeline with individual mapping validations based on the same input.

Also get webpack working again with live and hot reloads

NOTE: 
Tasks outstanding:

- Contract publishing
- Contract revalidation on input change
- Test refactor

@sabeen some styling updates are needed, especially around `read-only` pipelines and contracts

Related JIRA Ticket:
[AET-352](https://jira.ehealthafrica.org/browse/AET-352)

2019-02-13 10:25 UTC, obdulia-losantos commented
Could you remove the `VERSION` and `REVISION` files? :grimacing:

2019-02-19 10:14 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +                  : 'Not published'}
This is not the proper way of doing this. There should be an specific message for each id and not a dynamic one.

``` javascript
{ this.props.selectedContract.published_on &&
  <React.Fragment>
    <FormattedMessage
      id='pipeline.publish-status.yes'
      defaultMessage='Published on'
    /> { moment(this.props.selectedContract.published_on).format('MMMM DD, YYYY HH:mm') }
  </React.Fragment>
}
{ !this.props.selectedContract.published_on &&
  <FormattedMessage
    id='pipeline.publish-status.not'
    defaultMessage='Not published'
  />
}
```

2019-02-19 10:17 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/PipelineList.jsx
> +
Note: search for a javascript linter that complains with looooooooooooooooooooooooooog lines :unamused:

2019-02-19 10:18 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/PipelineList.jsx
> +                          : 'Not published'}
Same comment about messages...

2019-02-19 10:31 UTC, obdulia-losantos commented on docker-compose-base.yml
> +      WEBPACK_STATS_FILE: /code/aether/ui/assets/bundles/webpack-stats.json
This is useless.

2019-02-19 10:33 UTC, obdulia-losantos requested changes
I still need to test it locally, but apart from the "styling" issues only the messages comments need to be fixed.

2019-02-19 10:40 UTC, obdulia-losantos commented
Shouldn't this be **create passthrough CONTRACT**?

![image](https://user-images.githubusercontent.com/8459537/53009100-09953900-343b-11e9-9647-19f33b8fd347.png)

2019-02-19 15:00 UTC, adamvert commented
Can you take another look @obdulia-losantos @sabeen ?

2019-02-19 15:12 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +                  : 'Not published'}
Thanks!

2019-02-19 15:12 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/PipelineList.jsx
> +                          : 'Not published'}
Thanks again!

2019-02-20 10:20 UTC, obdulia-losantos submitted a review, later dismissed

2019-02-20 11:01 UTC, sabeen submitted a review, later dismissed

2019-02-20 11:34 UTC, obdulia-losantos submitted a review, later dismissed

2019-02-20 11:37 UTC, obdulia-losantos commented on aether-ui/aether/ui/assets/apps/pipeline/InfoButton.jsx
>  import React, { Component } from 'react'
Where is the LICENSE header?

2019-02-20 11:42 UTC, adamvert commented on aether-ui/aether/ui/assets/apps/pipeline/InfoButton.jsx
>  import React, { Component } from 'react'
😱

2019-02-20 12:03 UTC, obdulia-losantos approved these changes

2019-02-20 14:24 UTC, merged