feat: (ui) Contract settings with Identity Naming
eHealthAfrica/aether pull request #531
Opened 2019-03-21 08:28 UTC by lordmallam

Implements the new contract settings mockup [here](https://jira.ehealthafrica.org/browse/AET-483)
Allowing custom naming for Identity Entity Type.
Stops default contract creation on new pipelines
Allows Identity mappings to be generated on non-identity contracts multiple times

@sabeen please help with styling the identity generation segment. 😃

2019-04-09 09:36 UTC, admbtlr requested changes

2019-04-09 09:36 UTC, admbtlr commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +} from './redux'
Please order these lists alphabetically - it makes it easier to scan through them

2019-04-09 09:36 UTC, admbtlr commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +      !this.props.isNew
I looked at the rest of the file to try and understand what's happening here, and I think you might have a bug on line 86: you reference `this.state.isNew`, but I don't think `isNew` ever gets put into state. Should that line reference `this.props.isNew` instead?

2019-04-09 09:36 UTC, admbtlr commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +      !this.props.isNew
And now I realise that there's no test coverage on this code... can we get some tests please?

2019-04-09 09:36 UTC, admbtlr commented on aether-ui/aether/ui/assets/apps/pipeline/redux.jsx
> +  SET_CALL_BACK: 'set_call_back'
I don't think it's a good idea to store a callback function in Redux - let's talk through some other options

2019-04-09 09:36 UTC, admbtlr commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Settings.jsx
> +                that are identical with the input. If you choose this setting.
```suggestion
                that are identical with the input. If you choose this setting,
```

2019-04-09 09:36 UTC, admbtlr commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Settings.jsx
> +                  the data Alternatively, you can use the generate Entity Type
```suggestion
                  the data. Alternatively, you can use the generate Entity Type
```

2019-04-09 09:36 UTC, admbtlr commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Settings.jsx
> +                defaultMessage='All Entity Types and Mappings were generated automatically from the input'
```suggestion
                defaultMessage='All Entity Types and Mappings were automatically generated from the input data'
```

2019-04-15 07:51 UTC, sabeen commented
hi @lordmallam! I tested again, and found that the "add contract" button from the pipelines overview doesn't open the "new contract" section but the input section of the pipeline.

2019-04-15 08:33 UTC, lordmallam commented
> hi @lordmallam! I tested again, and found that the "add contract" button from the pipelines overview doesn't open the "new contract" section but the input section of the pipeline.

2019-04-24 14:17 UTC, admbtlr requested changes
Much better!

2019-04-24 14:17 UTC, admbtlr commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Settings.jsx
> +                  the data. Alternatively, you can use the generate Entity Type
Indent

2019-04-24 14:17 UTC, adamvert commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +        <NavBar showBreadcrumb cb={this.linksCallBack.bind(this)}>
Please put all the bind calls into the constructor, e.g.
```
this.linksCallBack = this.linksCallBack.bind(this);
```

It makes the JSX more readable and removes duplication.

2019-04-24 14:17 UTC, adamvert commented on aether-ui/aether/ui/assets/apps/pipeline/Pipeline.jsx
> +            onClick={this.onContracts.bind(this)}>
Here too

2019-04-24 14:17 UTC, adamvert commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Settings.jsx
> +            onSave={this.performSave.bind(this)} /> }
Here too

2019-04-24 14:17 UTC, adamvert commented on aether-ui/aether/ui/assets/apps/pipeline/sections/Settings.jsx
> +              onClick={this.onSave.bind(this, contract)}>
And here...

2019-04-24 16:11 UTC, admbtlr approved these changes

2019-04-25 07:09 UTC, merged