feat: implement gateway middleware
eHealthAfrica/aether pull request #544
Opened 2019-04-05 12:21 UTC by obdulia-losantos

2019-04-16 12:57 UTC, shawnsarwar submitted a review, later dismissed
Looks great! Let's get this sucker RC'd

2019-04-16 12:57 UTC, shawnsarwar commented on aether-common-library/aether/common/tests/test_urls.py
>      CAS_SERVER_URL='http://localhost:6666',
Are you calling the CAS_SERVER evil?

2019-04-16 12:58 UTC, obdulia-losantos commented on aether-common-library/aether/common/tests/test_urls.py
>      CAS_SERVER_URL='http://localhost:6666',
:smiling_imp:

2019-04-17 14:12 UTC, admbtlr requested changes
😍 😍 😍 😍 😍 😍 

Just a couple of VERY IMPORTANT CHANGES

2019-04-17 14:12 UTC, admbtlr commented on aether-common-library/aether/common/conf/urls.py
> +    #  values depending on the value of `settings.TESTING`. Without these
```suggestion
    # values depending on the value of `settings.TESTING`. Without these
```

2019-04-17 14:12 UTC, adamvert commented on aether-common-library/aether/common/utils.py
> +    return getattr(request, 'headers', {}).get(  # New in Django.2.2
```suggestion
    return getattr(request, 'headers', {}).get(  # New in Django 2.2
```

2019-04-17 14:22 UTC, admbtlr approved these changes

2019-04-17 14:30 UTC, merged