feat: (odk) Visualization decoration
eHealthAfrica/aether pull request #606
Opened 2019-06-30 11:06 UTC by lordmallam

Adds 2 decorators to schemas generated from xforms with `select`, `select1` and `odk:rank`

Decorators:
`@xformsType`: (Applied to all fields) A string indicating the original xform [type](https://docs.opendatakit.org/form-question-types)
`@xformOptions`: (Available for only select fields) A list of `{ 'label': 'Foo', 'value': 'foo' }` representing all available options of the field.

Limitations: This does not apply to select fields linked to datasources using `itemset`. Research on-going on how to effectively resolve datasource references.

2019-07-01 08:23 UTC, adamvert commented
According to the ticket, the fields should be called `@aether_lookup` and `@aether_extended_type`. Can you change them please?

2019-07-01 11:59 UTC, obdulia-losantos commented on aether-odk-module/aether/odk/api/xform_utils.py
> +            current_field['@aether_lookup'] = select_options if len(select_options) <= 20 else []
`if` within `if`? why not the following?
```python
if select_options and len(select_options) <= 20:
    current_field['@aether_lookup'] = select_options
```

2019-07-01 12:01 UTC, obdulia-losantos commented on aether-odk-module/aether/odk/api/xform_utils.py
> +        select_options = None
why don't you include all of this inside the `__get_xform_instance_skeleton` method and return another property like `choices`?

2019-07-02 16:06 UTC, obdulia-losantos commented on aether-odk-module/aether/odk/api/xform_utils.py
> +          as { lable: 'Foo', value: 'foo'}
typo?

2019-07-02 16:08 UTC, obdulia-losantos commented on aether-odk-module/aether/odk/api/xform_utils.py
> +                    if select_options and len(select_options) <= 20:
Could you change this magic number `20` with a constant like `SELECT_CHOICES_CUTOFF` of whatever you like most?

2019-07-02 16:26 UTC, obdulia-losantos commented on aether-odk-module/aether/odk/api/xform_utils.py
> +                select_options = None
You don't need this line.

2019-07-02 16:27 UTC, obdulia-losantos commented on aether-odk-module/aether/odk/api/tests/test_xform_utils.py
> +    # __get_xform_select_options as get_select_options,
_cleaning the house_

2019-07-02 16:29 UTC, obdulia-losantos commented on aether-odk-module/aether/odk/api/xform_utils.py
> +                                and '@ref' in option['label'] and option['label']['@ref'].startswith('jr:itext'):
simple is better

```python
if (
    isinstance(option.get('label'), dict) and
    option['label'].get('@ref', '').startswith('jr:itext')
):
```

2019-07-02 16:33 UTC, obdulia-losantos requested changes
Looks great, just a couple of small comments

2019-07-03 10:20 UTC, obdulia-losantos approved these changes
:clapper:

2019-07-03 10:31 UTC, merged