entity upsert with merge left or right options
eHealthAfrica/aether pull request #65
Opened 2018-01-25 12:09 UTC by lordmallam

#### What this PR does
Creates the entities/put endpoint to update, accepts merge options and an existing entity id

#### Usage
`/entities/[entity uuid]/?merge=[merge option]`
or 
include a merge property in the body
`{
...
"merge": "[merge option]" 
...
}`

#### Merge Options
`last_write_wins` : target payload takes primacy
`first_write_wins` : source payload takes primacy
`overwrite` : target overwrites source (no merge is performed)

####  Related JIRA Ticket
[AET-71](https://jira.ehealthafrica.org/browse/AET-71)

2018-01-25 14:43 UTC, shawnsarwar requested changes
Looks great overall. It may be difficult for API users to remember which integer based argument coincides with which merge strategy. I think a more descriptive string based arg would be preferable. Merge left and right aren't very clear. Perhaps something descriptive like, "overwrite", "prefer_new", and "prefer_existing".

2018-01-26 13:54 UTC, shawnsarwar approved these changes

2018-01-28 15:27 UTC, quesebifurcan requested changes

2018-01-28 15:27 UTC, quesebifurcan commented on aether-kernel/aether/kernel/api/serializers.py
> +    (utils.MergeOptions.perfer_new.value, 'Prefer New (Target to Source)'),
Spelling: "perfer" -> "prefer"?

2018-01-28 15:27 UTC, quesebifurcan commented on aether-kernel/aether/kernel/api/serializers.py
>      def create(self, validated_data):
Do we really want this logic inside of the `create` method? As I understood the issue, merge options need only be available when using `PUT` or `PATCH`. And if you override the `update` method instead, you would already have access to the instance id (and can skip the `update_id` parameter).

2018-01-28 15:27 UTC, quesebifurcan commented on aether-kernel/aether/kernel/api/serializers.py
> +            })
It would be good to have tests for this (to make sure we have 100% coverage of all if-branches).

2018-01-29 13:00 UTC, lordmallam commented on aether-kernel/aether/kernel/api/serializers.py
> +            })
Test included for merge option (fww)

2018-01-30 08:45 UTC, quesebifurcan requested changes

2018-01-30 08:45 UTC, quesebifurcan commented on aether-kernel/aether/kernel/api/serializers.py
> +    lookup_field = 'merge'
Quoting from Slack: 

> what do you think about putting the upsert logic in a separate function based view under its own endpoint? That would keep things decoupled and easily modifiable (no need to change the existing Entity.create method). Something like:
> 
> ```/entity-merge/<primary-key-of-target>?strategy=prefer_new```

This would mean having a separate (view) function (in `aether/kernel/views.py`) which contains all the merge logic. And there would be no need to touch this serializer. The problem here is that we're modifying `lookup_field`, which impacts both routing and the hyperlinks between serializers.

2018-01-30 12:59 UTC, quesebifurcan approved these changes

2018-01-30 13:09 UTC, merged