test: (kernel) submission validation
eHealthAfrica/aether pull request #677
Opened 2019-09-12 11:36 UTC by lordmallam

### Validates a submission payload using the provided `mappingset_id`
Reachable at `POST /submissions/validate/`

### JIRA ticket: [AET-468](https://jira.ehealthafrica.org/browse/AET-468)
expected body:
            ```{
                'mappingset': 'uuid',
                'payload': {}
            }```

expected response:
        ```{
            'is_valid': 'true||false',
            'entities': [],
            aether_errors: []
        }```

2019-09-12 12:03 UTC, obdulia-losantos commented on aether-kernel/aether/kernel/api/views.py
> +        mappings = models.MappingSet.objects.get(pk=mappingset_id).mappings.all()
do not used this method if multitenancy is enabled, it breaks security  :scream: 

```python
from django.shortcuts import get_object_or_404
from rest_framework.exceptions import PermissionDenied
from aether.django.sdk.multitenancy.utils import is_accessible_by_realm

mappingset = get_object_or_404(models.MappingSet.objects.all(), pk=mappingset_id)
if not is_accessible_by_realm(request, mappingset):
    raise PermissionDenied(_('Not accessible by this realm'))

mappings = mappingset.mappings.all()
```

2019-09-12 12:09 UTC, obdulia-losantos requested changes
I tiny security hole... :hole: :golfing_man:

2019-09-12 12:53 UTC, obdulia-losantos commented on aether-kernel/aether/kernel/api/views.py
> +        if not x:
:joy: 

Debug enabled :stuck_out_tongue_closed_eyes:

2019-09-12 13:13 UTC, lordmallam commented on aether-kernel/aether/kernel/api/views.py
> +        if not x:
🤣

2019-09-12 13:21 UTC, obdulia-losantos commented on aether-kernel/aether/kernel/api/views.py
> +                if ENTITY_EXTRACTION_ERRORS in submission_data and len(submission_data[ENTITY_EXTRACTION_ERRORS]):
python shortcut :woman_shrugging: 

```python
if submission_data.get(ENTITY_EXTRACTION_ERRORS):
```

If ENTITY_EXTRACTION_ERRORS is not in submission_data returns `None` then `False`
If submission_data[ENTITY_EXTRACTION_ERRORS] is an empty list then `False`
else `True`

_what we always forgot about python, chapter 3_

2019-09-12 13:22 UTC, obdulia-losantos commented on aether-kernel/aether/kernel/api/views.py
> +            schemas = {}
Another shortcut _chapter 4_

```python
schemas = {
    sd.name: sd.schema.definition
    for sd in mapping.schemadecorators.all()
}

```

2019-09-12 13:24 UTC, obdulia-losantos submitted a review, later dismissed
Note: read _chapter 5_ and explain it to me :books:  :wink:

2019-09-13 07:41 UTC, obdulia-losantos approved these changes

2019-09-13 07:42 UTC, merged