test: improved GUID regex matching
eHealthAfrica/aether pull request #680
Opened 2019-09-23 03:41 UTC by jirihofman

Shorter and (I think) more precise testing with regex. Found at https://www.regextester.com/99148. It does all the previous code did
- checks length
- checks `-` positions

and more
- checks allowed characters for GUID
- is one liner :)

2019-09-23 08:24 UTC, obdulia-losantos approved these changes
:dart:

2019-09-23 09:15 UTC, lordmallam submitted a review, later dismissed

2019-12-02 10:06 UTC, obdulia-losantos requested changes
@jirihofman  Could you fix the tests?

```text
standard: Use JavaScript Standard Style (https://standardjs.com)
  /code/apps/utils/index.spec.jsx:45:43: Unnecessary escape character: \-.
  /code/apps/utils/index.spec.jsx:45:59: Unnecessary escape character: \-.
  /code/apps/utils/index.spec.jsx:45:75: Unnecessary escape character: \-.
  /code/apps/utils/index.spec.jsx:45:91: Unnecessary escape character: \-.
```

2019-12-02 10:08 UTC, obdulia-losantos commented
@jirihofman we fixed our problems with the tests and we are ready to merge this PR but the tests are failing. Would you mind fixing them? I'll merge this PR afterwards.

Thanks for your patience and sorry for the delay.

2019-12-03 13:38 UTC, obdulia-losantos approved these changes

2019-12-03 13:48 UTC, merged