feat(common): CSVRenderer: parse header labels
eHealthAfrica/aether pull request #69
Opened 2018-01-26 13:50 UTC by obdulia-losantos

Continues https://jira.ehealthafrica.org/browse/AET-125

Include in the url the param `parse_columns` with the rules to generate csv headers. See tests for more examples.

In this use case: `parse_columns=remove-prefix:payload.`

For CHAMPS: `rule_sep=$&parse_columns=remove-prefix$payload.,replace$.$:`

2018-01-26 13:58 UTC, admbtlr requested changes

2018-01-26 13:58 UTC, admbtlr commented on aether-common-module/aether/common/drf/renderers.py
> +    if rule.startswith('replace:'):
Wow, this is amazing, you actually read my mind... I'd forgotten that the final thing we need to do for CHAMPS to change the '.' separator on the column headings into a ':' 

💯!

2018-01-26 13:58 UTC, admbtlr commented on aether-common-module/aether/common/drf/renderers.py
> +    if rule.startswith('split:') and rule != 'split:':
Is this any different to `replace:<sep>: `?

2018-01-26 14:02 UTC, obdulia-losantos commented on aether-common-module/aether/common/drf/renderers.py
> +    if rule.startswith('split:') and rule != 'split:':
Nop, just a shortcut of `replace:<sep>: :` :thinking:

2018-01-26 14:03 UTC, obdulia-losantos commented on aether-common-module/aether/common/drf/renderers.py
> +    if rule.startswith('replace:'):
In this case I'm not sure if I should use another rule separator like... `|` maybe

2018-01-26 14:03 UTC, admbtlr commented on aether-common-module/aether/common/drf/renderers.py
> +    if rule.startswith('split:') and rule != 'split:':
OK cool, just checking

2018-01-26 14:06 UTC, admbtlr commented on aether-common-module/aether/common/drf/renderers.py
> +    if rule.startswith('replace:'):
`\:`?

2018-01-26 14:11 UTC, obdulia-losantos commented on aether-common-module/aether/common/drf/renderers.py
> +    if rule.startswith('replace:'):
I meant `replace|.|:` I'm quite sure that there are no `|` in the object keys :crossed_fingers:

2018-01-26 14:24 UTC, obdulia-losantos commented on aether-common-module/aether/common/drf/renderers.py
> +    if rule.startswith('replace:'):
```
self.assertEqual(apply_label_rules(['replace:.:\:'], 'a.bcd'), 'a:bcd')

AssertionError: 'a\bcd' != 'a:bcd'
- a\bcd
+ a:bcd
```

2018-01-29 09:11 UTC, admbtlr approved these changes

2018-01-29 09:20 UTC, merged