Aet 37 entity linking
eHealthAfrica/aether pull request #79
Opened 2018-02-12 12:46 UTC by lordmallam

#### What does this PR do??
Includes linked entity data as nested objects on an entity `GET` request

#### How to test
Make a `GET` request on a entity with a `include_linked_data` and `depth(optional)` query strings
`/entities/<entityId>/?include_linked_data=true&depth=2`
This should return nested linked entities

#### Related JIRA ticket
[AET](https://jira.ehealthafrica.org/browse/AET-37)

2018-02-12 15:50 UTC, quesebifurcan requested changes
Looks good, great work!

Added some comments, but would like to test it properly. Which schemas and submissions data did you use for testing locally? Can you share them somehow?

2018-02-12 15:50 UTC, quesebifurcan commented on aether-kernel/aether/kernel/api/views.py
> +        include_linked_data = request.GET.get('include_linked_data')
You can use `query_params` here instead of `GET`. See: http://www.django-rest-framework.org/api-guide/requests/#query_params

2018-02-12 15:50 UTC, quesebifurcan commented on aether-kernel/aether/kernel/api/views.py
> +def get_entity_linked_data(entity, request, depth, start_depth=0):
Test coverage drops from 84 to 81 percent in this PR -- we need to make sure all new functions and classes are properly covered, so please add a couple of tests for this function.

2018-02-12 15:50 UTC, quesebifurcan commented on aether-kernel/aether/kernel/api/views.py
> +    def retrieve(self, request, pk=None):
Same here -- tests please :-)

2018-02-12 15:50 UTC, quesebifurcan commented on aether-kernel/aether/kernel/api/views.py
> +                depth = 1
Maybe it's possible to use only `depth` here and skip `include_linked_data`? Since we're checking `depth` anyway, `include_linked_data` is a bit redundant.
If depth is present in the query params, attempt to retrieve linked data; otherwise, skip this entire block.

2018-02-12 15:59 UTC, lordmallam commented on aether-kernel/aether/kernel/api/views.py
> +        include_linked_data = request.GET.get('include_linked_data')
For sample data, I ran the `./generate.sh` script from the `dev-demo` branch against the endpoints

2018-02-12 16:15 UTC, quesebifurcan commented on aether-kernel/aether/kernel/api/views.py
> +        include_linked_data = request.GET.get('include_linked_data')
Ok, thanks! I didn't get that branch to work, but `dev-demo-confluent` seems to generate entities.

2018-02-12 16:40 UTC, quesebifurcan requested changes

2018-02-12 16:40 UTC, quesebifurcan commented on aether-kernel/aether/kernel/api/views.py
> +                    Response('' + start_depth)
What is this line doing?

2018-02-12 16:40 UTC, quesebifurcan commented on aether-kernel/aether/kernel/api/views.py
> +                    linked_entity, many=True, context={'request': request}).data[0]
We would probably need to put the payload of the linked object where the id should have been.

Guideline: the entity with resolved links _must_ conform to the same schema as the entity without resolved links (otherwise other validations would fail).

For example:

```
{                                                                                                                                                                       
  "payload": {                                                                                                                                                          
    "id": "46f0d0f3-7117-497a-a2d4-96b8e88072f9",                                                                                                                       
    "_id": "220af2d0-641e-44ae-9903-d754e24ce07a",                                                                                                                      
    "age": 98,                                                                                                                                                          
    "isAlive": true,                                                                                                                                                    
    "lastName": "knight",                                                                                                                                               
    "firstName": "lee",                                                                                                                                                 
    "householdID": {                                                                                                                                                    
      "id": "05151ef6-f819-4b15-8a5a-132c4b0927b7",                                                                                                                     
      "_id": "38a722a5-f96d-460f-8c18-b63a1ae7efb4",                                                                                                                    
      "sectionID": "2",                                                                                                                                                 
      "hasBedNets": true,                                                                                                                                               
      "locationID": "d795419e-1e02-45fc-993a-e9fbdb5d2396",                                                                                                             
      "headOfHouseHold": "46f0d0f3-7117-497a-a2d4-96b8e88072f9",                                                                                                        
      "locationID": {                                                                                                                                                   
        "id": "d795419e-1e02-45fc-993a-e9fbdb5d2396",                                                                                                                   
        "_id": "53df87f3-d9b1-46ac-8424-5fab8f325253",                                                                                                                  
        "lat": 6.976889,                                                                                                                                                
        "lng": -9.059241        
```
(Removed some fields for simplicity)

Ping @shawnsarwar

2018-02-12 16:45 UTC, shawnsarwar commented on aether-kernel/aether/kernel/api/views.py
> +                depth = 1
I agree that depth would be sufficient. If depth is greater than the max depth we support (3), we should probably have an error as well.

2018-02-12 16:48 UTC, quesebifurcan commented on aether-kernel/aether/kernel/api/views.py
> +                    linked_entity, many=True, context={'request': request}).data[0]
Or some other solution, I'll bring it up in the channel.

2018-02-19 11:35 UTC, lordmallam commented on aether-kernel/aether/kernel/api/views.py
> +    def retrieve(self, request, pk=None):
Included tests for this

2018-02-21 08:56 UTC, quesebifurcan approved these changes

2018-02-22 08:32 UTC, merged