Aet 162 add kong component
eHealthAfrica/aether pull request #87
Opened 2018-02-23 13:29 UTC by lordmallam

#### What does this PR do?
Adds Kong as a component to the docker compose structure reachable on kong admin: `http://kong:8001` kong apis: `http://kong:8000`

#### How to test
Run `docker-compose up --build kernel`
Kong container is started with an ephemeral `kong-migration` container that handles migrations to the db
Kong admin should be reachable via `http://kong:8001` from within the `kernel` container or `kong.aether.local:8001` remotely (this requires that `kong.aether.local` be added to the /etc/host file)

#### Related JIRA ticket
[AET-162](https://jira.ehealthafrica.org/browse/AET-162)

2018-02-23 13:41 UTC, shawnsarwar approved these changes
Looks good. I can hit it on localhost:8001

2018-02-23 14:33 UTC, admbtlr requested changes

2018-02-23 14:33 UTC, admbtlr commented on docker-compose-base.yml
> +version: "2.1"
This is probably a breaking change, isn't it? If so, this should be `3.0`

2018-02-23 15:50 UTC, MrPink commented on docker-compose-base.yml
> +version: "2.1"
This is the docker-compose version, what does the minor release fix @lordmallam

2018-02-23 15:50 UTC, MrPink commented on docker-compose-base.yml
> +version: "2.1"
This is the docker-compose version, what does the minor release fix @lordmallam

2018-02-23 16:00 UTC, admbtlr commented on docker-compose-base.yml
> +version: "2.1"
D'oh! Ignore me...

2018-02-23 16:04 UTC, admbtlr commented on docker-compose-base.yml
> +version: "2.1"
@MrPink I'm going to hit approve, can you please hit "Request changes" until @lordmallam answers your question?

2018-02-23 16:05 UTC, admbtlr approved these changes

2018-02-23 16:24 UTC, quesebifurcan commented on docker-compose-base.yml
> +      - PSOTGRES_DB=kong
spelling -- `PSOTGRES_DB` -> `POSTGRES_DB`?

2018-02-26 08:06 UTC, lordmallam commented on docker-compose-base.yml
> +version: "2.1"
@MrPink `2.1` allows the use of `depends_on > condition`  for health checks

2018-02-26 09:09 UTC, MrPink approved these changes

2018-02-26 09:10 UTC, MrPink commented on docker-compose-base.yml
> +version: "2.1"
@lordmallam that's awesome :-) finally!

2018-02-26 09:28 UTC, merged