Chore: add helm
eHealthAfrica/aether pull request #98
Opened 2018-03-07 10:39 UTC by MrPink

Welcome to Helm! More information about Helm can be found here https://helm.sh/

**These will most likely evolve in time and come with fewer defaults**

* This allows us to package Aether Kubernetes resources as Helm packages which removes the complexity of distributing these resources in an organised and efficient manner. This is comparable to Debian's APT package system

* We host these Charts on http://charts.eha.im:8080/api/charts 
* The Helm charts use an override YAML where we can specify things to specific to the environment

**TO DO**
* Helm release and deployment workflow using Travis CI

2018-03-07 11:07 UTC, quesebifurcan requested changes

2018-03-07 11:07 UTC, quesebifurcan commented on helm/kernel/values.yaml
> +trusted_origins: .ehealthafrica.org
Not sure if `.ehealthafrica.org` is enough -- we might need `.gather2.org` instead/as well. Let's test and see.

2018-03-07 11:07 UTC, quesebifurcan commented on helm/odk/templates/NOTES.txt
> +  export SERVICE_IP=$(kubectl get svc --namespace {{ .Release.Namespace }} {{ template "odk.fullname" . }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
Does the helm linter catch jsonpath lookup errors?

2018-03-07 11:07 UTC, quesebifurcan commented on helm/odk/templates/db-init-config-map.yaml
> +    psql -c "GRANT ALL PRIVILEGES ON DATABASE $RDS_DB_NAME TO $RDS_USERNAME;"
Should we run bash scripts with some options perhaps?
`set -e` or `set -Eeuo(x) pipefail` (depending on the context)?

2018-03-07 11:45 UTC, MrPink commented on helm/odk/templates/db-init-config-map.yaml
> +    psql -c "GRANT ALL PRIVILEGES ON DATABASE $RDS_DB_NAME TO $RDS_USERNAME;"
well caught, I think `set -e` suffices

2018-03-07 11:46 UTC, MrPink commented on helm/odk/templates/NOTES.txt
> +  export SERVICE_IP=$(kubectl get svc --namespace {{ .Release.Namespace }} {{ template "odk.fullname" . }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
this outside the boundary of Helm's duties

2018-03-07 12:46 UTC, quesebifurcan submitted a review, later dismissed
Great! Looks good to me

2018-03-12 11:08 UTC, quesebifurcan submitted a review, later dismissed

2018-03-12 11:17 UTC, quesebifurcan approved these changes

2018-03-12 11:36 UTC, merged